import 'server-only';
import { and, asc, desc, eq, inArray, lt, lte, or } from 'drizzle-orm';
import {
  ApiError,
  type AssetCreate,
  type AssetDto,
  type AssetListQuery,
  type AssetUpdate,
  type Page,
  type WarrantyCreate,
} from '@simplexd/contracts';
import { getDb, schema, withActor, type DbExecutor } from '@simplexd/db';
import { assertAllowed, authorizeAny, type ResourceRef } from '@simplexd/domain/authz';
import { warrantyStatus } from '@simplexd/domain/rentals';
import { recordAudit } from '@/lib/audit';
import type { RequestIdentity } from '@/lib/auth/session';
import { requireProperty } from '@/server/properties/access';
import {
  FEATURES,
  ctxFor,
  decodeCursor,
  encodeCursor,
  isStaffIdentity,
  requireFlag,
  requireUserId,
  today,
  type ServiceOptions,
} from '@/server/rentals/shared';

/**
 * Asset register with warranty dates and service recurrence (preventive
 * maintenance expansion, `expansion.preventive_maintenance`). Owners manage
 * their own register (`org.properties.manage`); staff through
 * `maintenance.manage`. Recurring work orders are generated by the worker
 * from `next_service_at` and `service_interval_days`.
 */

type AssetRow = typeof schema.assets.$inferSelect;
type WarrantyRow = typeof schema.warranties.$inferSelect;

function ref(organizationId: string, id?: string): ResourceRef {
  return { type: 'asset', id, organizationId };
}

function assertManage(identity: RequestIdentity, r: ResourceRef): void {
  assertAllowed(authorizeAny(identity.actor, [{ staff: 'maintenance.manage' }, { org: 'org.properties.manage' }], r));
}

function assertRead(identity: RequestIdentity, r: ResourceRef): void {
  assertAllowed(
    authorizeAny(identity.actor, [{ staff: 'maintenance.manage' }, { staff: 'customers.read' }, { staff: 'estates.manage' }, { org: 'org.read' }], r),
  );
}

function toDto(row: AssetRow, warranties: WarrantyRow[], asOf: string): AssetDto {
  return {
    id: row.id,
    organizationId: row.organizationId,
    propertyId: row.propertyId,
    estateId: row.estateId,
    name: row.name,
    category: row.category,
    serialNumber: row.serialNumber,
    installedAt: row.installedAt,
    condition: row.condition,
    nextServiceAt: row.nextServiceAt,
    serviceIntervalDays: row.serviceIntervalDays,
    notes: row.notes,
    warranties: warranties.map((w) => ({
      id: w.id,
      assetId: w.assetId,
      provider: w.provider,
      reference: w.reference,
      startsAt: w.startsAt,
      expiresAt: w.expiresAt,
      status: warrantyStatus(w.expiresAt, asOf),
      documentFileId: w.documentFileId,
      createdAt: w.createdAt.toISOString(),
    })),
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

async function withWarranties(tx: DbExecutor, rows: AssetRow[]): Promise<AssetDto[]> {
  if (rows.length === 0) return [];
  const warranties = await tx
    .select()
    .from(schema.warranties)
    .where(inArray(schema.warranties.assetId, rows.map((r) => r.id)))
    .orderBy(asc(schema.warranties.expiresAt));
  const asOf = today();
  return rows.map((r) => toDto(r, warranties.filter((w) => w.assetId === r.id), asOf));
}

async function requireAsset(tx: DbExecutor, identity: RequestIdentity, id: string, mode: 'read' | 'manage'): Promise<AssetRow> {
  const [row] = await tx.select().from(schema.assets).where(eq(schema.assets.id, id));
  if (!row) throw new ApiError('not_found', 'asset not found');
  if (mode === 'manage') assertManage(identity, ref(row.organizationId, row.id));
  else assertRead(identity, ref(row.organizationId, row.id));
  return row;
}

export async function createAsset(identity: RequestIdentity, input: AssetCreate, options: ServiceOptions = {}): Promise<AssetDto> {
  requireFlag(identity, FEATURES.preventiveMaintenance);
  requireUserId(identity);
  return withActor(getDb(), ctxFor(identity, options), async (tx) => {
    const property = await requireProperty(tx, identity, input.propertyId, 'read');
    assertManage(identity, ref(property.organizationId));
    if (input.estateId) {
      const [estate] = await tx.select({ id: schema.estates.id }).from(schema.estates).where(and(eq(schema.estates.id, input.estateId), eq(schema.estates.organizationId, property.organizationId)));
      if (!estate) throw new ApiError('validation_failed', 'unknown estate for this organisation');
    }
    const [row] = await tx
      .insert(schema.assets)
      .values({
        organizationId: property.organizationId,
        propertyId: property.id,
        estateId: input.estateId ?? property.estateId ?? null,
        name: input.name,
        category: input.category,
        serialNumber: input.serialNumber ?? null,
        installedAt: input.installedAt ?? null,
        condition: input.condition,
        nextServiceAt: input.nextServiceAt ?? null,
        serviceIntervalDays: input.serviceIntervalDays ?? null,
        notes: input.notes ?? null,
      })
      .returning();
    await recordAudit(tx, identity, {
      action: 'asset.created',
      entityType: 'asset',
      entityId: row!.id,
      organizationId: property.organizationId,
      after: { name: input.name, category: input.category, nextServiceAt: input.nextServiceAt ?? null },
      correlationId: options.correlationId,
    });
    return (await withWarranties(tx, [row!]))[0]!;
  });
}

export async function updateAsset(identity: RequestIdentity, id: string, input: AssetUpdate, options: ServiceOptions = {}): Promise<AssetDto> {
  requireFlag(identity, FEATURES.preventiveMaintenance);
  requireUserId(identity);
  return withActor(getDb(), ctxFor(identity, options), async (tx) => {
    const current = await requireAsset(tx, identity, id, 'manage');
    const [row] = await tx
      .update(schema.assets)
      .set({
        ...(input.name !== undefined ? { name: input.name } : {}),
        ...(input.category !== undefined ? { category: input.category } : {}),
        ...(input.serialNumber !== undefined ? { serialNumber: input.serialNumber } : {}),
        ...(input.installedAt !== undefined ? { installedAt: input.installedAt } : {}),
        ...(input.condition !== undefined ? { condition: input.condition } : {}),
        ...(input.nextServiceAt !== undefined ? { nextServiceAt: input.nextServiceAt } : {}),
        ...(input.serviceIntervalDays !== undefined ? { serviceIntervalDays: input.serviceIntervalDays } : {}),
        ...(input.notes !== undefined ? { notes: input.notes } : {}),
        ...(input.estateId !== undefined ? { estateId: input.estateId } : {}),
      })
      .where(eq(schema.assets.id, id))
      .returning();
    await recordAudit(tx, identity, {
      action: 'asset.updated',
      entityType: 'asset',
      entityId: id,
      organizationId: current.organizationId,
      before: { name: current.name, condition: current.condition, nextServiceAt: current.nextServiceAt },
      after: input,
      correlationId: options.correlationId,
    });
    return (await withWarranties(tx, [row!]))[0]!;
  });
}

export async function getAsset(identity: RequestIdentity, id: string): Promise<AssetDto> {
  requireFlag(identity, FEATURES.preventiveMaintenance);
  return withActor(getDb(), identity.ctx, async (tx) => (await withWarranties(tx, [await requireAsset(tx, identity, id, 'read')]))[0]!);
}

export async function listAssets(identity: RequestIdentity, query: AssetListQuery): Promise<Page<AssetDto>> {
  requireFlag(identity, FEATURES.preventiveMaintenance);
  requireUserId(identity);
  const staff = isStaffIdentity(identity);
  const orgId = staff ? (query.organizationId ?? null) : identity.ctx.organizationId;
  if (!staff && !orgId) return { items: [], nextCursor: null };
  if (orgId) assertRead(identity, ref(orgId));
  const cursor = decodeCursor(query.cursor);
  return withActor(getDb(), identity.ctx, async (tx) => {
    const rows = await tx
      .select()
      .from(schema.assets)
      .where(
        and(
          orgId ? eq(schema.assets.organizationId, orgId) : undefined,
          query.propertyId ? eq(schema.assets.propertyId, query.propertyId) : undefined,
          query.estateId ? eq(schema.assets.estateId, query.estateId) : undefined,
          query.serviceDueBefore ? lte(schema.assets.nextServiceAt, query.serviceDueBefore) : undefined,
          cursor ? or(lt(schema.assets.createdAt, cursor.createdAt), and(eq(schema.assets.createdAt, cursor.createdAt), lt(schema.assets.id, cursor.id))) : undefined,
        ),
      )
      .orderBy(desc(schema.assets.createdAt), desc(schema.assets.id))
      .limit(query.limit + 1);
    const page = rows.slice(0, query.limit);
    const last = rows.length > query.limit ? page[page.length - 1] : null;
    return { items: await withWarranties(tx, page), nextCursor: last ? encodeCursor(last.createdAt, last.id) : null };
  });
}

export async function addWarranty(identity: RequestIdentity, assetId: string, input: WarrantyCreate, options: ServiceOptions = {}): Promise<AssetDto> {
  requireFlag(identity, FEATURES.preventiveMaintenance);
  requireUserId(identity);
  return withActor(getDb(), ctxFor(identity, options), async (tx) => {
    const asset = await requireAsset(tx, identity, assetId, 'manage');
    if (input.startsAt && input.startsAt > input.expiresAt) throw new ApiError('validation_failed', 'warranty expires before it starts');
    const [w] = await tx
      .insert(schema.warranties)
      .values({
        assetId,
        provider: input.provider,
        reference: input.reference ?? null,
        startsAt: input.startsAt ?? null,
        expiresAt: input.expiresAt,
        documentFileId: input.documentFileId ?? null,
      })
      .returning();
    await recordAudit(tx, identity, {
      action: 'warranty.added',
      entityType: 'asset',
      entityId: assetId,
      organizationId: asset.organizationId,
      after: { warrantyId: w!.id, provider: input.provider, expiresAt: input.expiresAt },
      correlationId: options.correlationId,
    });
    return (await withWarranties(tx, [asset]))[0]!;
  });
}
