import { z } from 'zod';
import {
  adminMarketListQuerySchema,
  adminMarketListResponseSchema,
  auditEventDtoSchema,
  auditListQuerySchema,
  dataPolicyPatchSchema,
  exportQuerySchema,
  featureFlagPatchSchema,
  freshnessPolicyUpsertSchema,
  importApplySchema,
  importDtoSchema,
  importPreviewRequestSchema,
  listRoutes,
  marketBulkActionSchema,
  marketFlagCreateSchema,
  marketFlagPatchSchema,
  marketMergeSchema,
  marketMoveSchema,
  marketPatchSchema,
  marketRevisionDtoSchema,
  marketRollbackSchema,
  marketTransitionSchema,
  marketUpsertSchema,
  neighborhoodCreateSchema,
  neighborhoodPatchSchema,
  observationCreateInputSchema,
  observationListQuerySchema,
  observationReviewInputSchema,
  partnerVerifySchema,
  rankingPolicyActivateSchema,
  rankingPolicyCreateSchema,
  rankingPolicyDtoSchema,
  rankingPolicyPatchSchema,
  registerRoute,
  researchTaskCreateSchema,
  researchTaskPatchSchema,
  revisionCompareQuerySchema,
  serviceCoverageUpdateSchema,
  settingPatchSchema,
  sourceCreateSchema,
  sourceListQuerySchema,
  sourcePatchSchema,
  staffDirectoryQuerySchema,
  staffRoleChangeSchema,
  uuidSchema,
  type RouteSpec,
} from '@simplexd/contracts';

/**
 * OpenAPI registrations for the admin console: market-data administration,
 * platform settings, access management and the audit log. Registration is
 * idempotent so hot reloads never trip the duplicate-operation guard.
 */

const idParams = z.object({ id: uuidSchema });
const keyParams = z.object({ key: z.string() });
const versionParams = z.object({ version: z.coerce.number().int() });
const items = (item: z.ZodTypeAny) => z.object({ items: z.array(item) });

function register(spec: RouteSpec): void {
  if (listRoutes().some((r) => r.operationId === spec.operationId)) return;
  registerRoute(spec);
}

const tags = ['Admin: market data'];
const platformTags = ['Admin: platform'];
const accessTags = ['Admin: access'];

const specs: RouteSpec[] = [
  {
    method: 'get',
    path: '/api/v1/admin/markets',
    summary: 'List markets including drafts',
    description:
      'Filters by state, zone, publication state, availability, recommendation status and pending reviews. Stable offset pagination for tables.',
    tags,
    operationId: 'adminListMarkets',
    auth: 'staff',
    request: { query: adminMarketListQuerySchema },
    responses: { 200: { description: 'Markets page', body: adminMarketListResponseSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets',
    summary: 'Create a draft market',
    description:
      'Coordinates must fall inside Nigeria (lon 2.5–15, lat 4–14). Creates revision 1 and an audit entry.',
    tags,
    operationId: 'adminCreateMarket',
    auth: 'staff',
    request: { body: marketUpsertSchema },
    responses: { 201: { description: 'Created market' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/bulk',
    summary: 'Bulk publish or unpublish with preview',
    tags,
    operationId: 'adminBulkMarkets',
    auth: 'staff',
    request: { body: marketBulkActionSchema },
    responses: { 200: { description: 'Per-market outcomes' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}',
    summary: 'Get a market for administration',
    tags,
    operationId: 'adminGetMarket',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Market detail' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/markets/{id}',
    summary: 'Edit a market with optimistic concurrency',
    description:
      'expectedVersion must match; the change is snapshotted into market_revisions and audited with before/after. Published markets require market_data.publish.',
    tags,
    operationId: 'adminPatchMarket',
    auth: 'staff',
    request: { params: idParams, body: marketPatchSchema },
    responses: { 200: { description: 'Updated market' }, 409: { description: 'version_conflict' } },
  },
  ...(['publish', 'unpublish', 'archive', 'restore'] as const).map((action): RouteSpec => ({
    method: 'post',
    path: `/api/v1/admin/markets/{id}/${action}`,
    summary: `${action[0]!.toUpperCase()}${action.slice(1)} a market`,
    description:
      action === 'archive' ? 'Markets with linked records are archived, never deleted.' : undefined,
    tags,
    operationId: `adminMarket${action[0]!.toUpperCase()}${action.slice(1)}`,
    auth: 'staff',
    request: { params: idParams, body: marketTransitionSchema },
    responses: { 200: { description: 'Updated market' } },
  })),
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/move',
    summary: 'Move the market reference point',
    tags,
    operationId: 'adminMoveMarket',
    auth: 'staff',
    request: { params: idParams, body: marketMoveSchema },
    responses: { 200: { description: 'Updated market' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/merge',
    summary: 'Merge a duplicate market into a target',
    description:
      'Repoints interpretations (as new versions), supplier links, research tasks, properties, projects, service requests, flags and neighborhoods; archives the source with mergedIntoMarketId.',
    tags,
    operationId: 'adminMergeMarket',
    auth: 'staff',
    request: { params: idParams, body: marketMergeSchema },
    responses: { 200: { description: 'Merge result with repointed counts' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/revisions',
    summary: 'Revision history or side-by-side diff',
    tags,
    operationId: 'adminMarketRevisions',
    auth: 'staff',
    request: { params: idParams, query: revisionCompareQuerySchema },
    responses: { 200: { description: 'Revisions', body: items(marketRevisionDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/rollback',
    summary: 'Roll back to a revision (creates a new revision)',
    tags,
    operationId: 'adminRollbackMarket',
    auth: 'staff',
    request: { params: idParams, body: marketRollbackSchema },
    responses: { 200: { description: 'Updated market' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/neighborhoods',
    summary: 'List neighborhoods',
    tags,
    operationId: 'adminListNeighborhoods',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Neighborhoods' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/neighborhoods',
    summary: 'Create a neighborhood (boundary validated by PostGIS)',
    tags,
    operationId: 'adminCreateNeighborhood',
    auth: 'staff',
    request: { params: idParams, body: neighborhoodCreateSchema },
    responses: { 201: { description: 'Neighborhood' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/markets/{id}/neighborhoods/{nid}',
    summary: 'Edit or archive a neighborhood',
    tags,
    operationId: 'adminPatchNeighborhood',
    auth: 'staff',
    request: {
      params: z.object({ id: uuidSchema, nid: uuidSchema }),
      body: neighborhoodPatchSchema,
    },
    responses: { 200: { description: 'Neighborhood' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/coverage',
    summary: 'Service availability per market',
    tags,
    operationId: 'adminGetCoverage',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Coverage rows' } },
  },
  {
    method: 'put',
    path: '/api/v1/admin/markets/{id}/coverage',
    summary: 'Update service availability (independent of publication)',
    tags,
    operationId: 'adminUpdateCoverage',
    auth: 'staff',
    request: { params: idParams, body: serviceCoverageUpdateSchema },
    responses: { 200: { description: 'Coverage rows' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/flags',
    summary: 'List market flags',
    tags,
    operationId: 'adminListFlags',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Flags' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/flags',
    summary: 'Create a market flag',
    tags,
    operationId: 'adminCreateFlag',
    auth: 'staff',
    request: { params: idParams, body: marketFlagCreateSchema },
    responses: { 201: { description: 'Flag' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/markets/{id}/flags/{fid}',
    summary: 'Amend or deactivate a flag',
    tags,
    operationId: 'adminPatchFlag',
    auth: 'staff',
    request: { params: z.object({ id: uuidSchema, fid: uuidSchema }), body: marketFlagPatchSchema },
    responses: { 200: { description: 'Flag' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/research-tasks',
    summary: 'List research tasks',
    tags,
    operationId: 'adminListResearchTasks',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Tasks' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/markets/{id}/research-tasks',
    summary: 'Create a research task (separate researcher and reviewer)',
    tags,
    operationId: 'adminCreateResearchTask',
    auth: 'staff',
    request: { params: idParams, body: researchTaskCreateSchema },
    responses: { 201: { description: 'Task' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/markets/{id}/research-tasks/{tid}',
    summary: 'Update a research task',
    tags,
    operationId: 'adminPatchResearchTask',
    auth: 'staff',
    request: {
      params: z.object({ id: uuidSchema, tid: uuidSchema }),
      body: researchTaskPatchSchema,
    },
    responses: { 200: { description: 'Task' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/markets/{id}/observations',
    summary: 'Local observations and statewide context for a market',
    tags,
    operationId: 'adminMarketObservations',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Local and statewide observations' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/sources',
    summary: 'List sources',
    tags,
    operationId: 'adminListSources',
    auth: 'staff',
    request: { query: sourceListQuerySchema },
    responses: { 200: { description: 'Sources' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/sources',
    summary: 'Create a source',
    tags,
    operationId: 'adminCreateSource',
    auth: 'staff',
    request: { body: sourceCreateSchema },
    responses: { 201: { description: 'Source' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/sources/{id}',
    summary: 'Get a source',
    tags,
    operationId: 'adminGetSource',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Source' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/sources/{id}',
    summary: 'Edit a source',
    tags,
    operationId: 'adminPatchSource',
    auth: 'staff',
    request: { params: idParams, body: sourcePatchSchema },
    responses: { 200: { description: 'Source' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/observations',
    summary: 'Observation review queue',
    tags,
    operationId: 'adminListObservations',
    auth: 'staff',
    request: { query: observationListQuerySchema },
    responses: { 200: { description: 'Observations page' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/observations',
    summary: 'Record an immutable observation and submit it for review',
    tags,
    operationId: 'adminCreateObservation',
    auth: 'staff',
    request: { body: observationCreateInputSchema },
    responses: { 201: { description: 'Observation with interpretation v1' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/observations/{id}',
    summary: 'Observation with interpretation history, reviews and comparables',
    tags,
    operationId: 'adminGetObservation',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Observation detail' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/observations/{id}/review',
    summary: 'Apply a review decision (new interpretation version)',
    description:
      'publish and mark_rank_eligible require market_data.publish (MFA) by a different user than the submitter (own_work). Local medians below publication.min_comparables cannot be published unless publishAsContextual is set, which records the reason and keeps rank_eligible false.',
    tags,
    operationId: 'adminReviewObservation',
    auth: 'staff',
    request: { params: idParams, body: observationReviewInputSchema },
    responses: {
      200: { description: 'Updated observation' },
      422: { description: 'insufficient_evidence' },
    },
  },
  {
    method: 'get',
    path: '/api/v1/admin/market-imports',
    summary: 'Import history',
    tags,
    operationId: 'adminListImports',
    auth: 'staff',
    responses: { 200: { description: 'Imports', body: items(importDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/market-imports/preview',
    summary: 'Preview a seed JSON or observations CSV import (dry run)',
    tags,
    operationId: 'adminPreviewImport',
    auth: 'staff',
    request: { body: importPreviewRequestSchema },
    responses: {
      201: { description: 'Preview with row-level errors and conflicts', body: importDtoSchema },
    },
  },
  {
    method: 'get',
    path: '/api/v1/admin/market-imports/{id}',
    summary: 'Get an import',
    tags,
    operationId: 'adminGetImport',
    auth: 'staff',
    request: { params: idParams },
    responses: { 200: { description: 'Import', body: importDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/market-imports/{id}/apply',
    summary: 'Apply a previewed import',
    tags,
    operationId: 'adminApplyImport',
    auth: 'staff',
    request: { params: idParams, body: importApplySchema },
    responses: { 200: { description: 'Import', body: importDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/exports/{file}',
    summary: 'Export markets or observations as JSON or CSV with provenance',
    tags,
    operationId: 'adminExport',
    auth: 'staff',
    request: {
      params: z.object({
        file: z.enum(['markets.json', 'markets.csv', 'observations.json', 'observations.csv']),
      }),
      query: exportQuerySchema,
    },
    responses: { 200: { description: 'File download' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/ranking-policies',
    summary: 'List ranking policy versions',
    tags,
    operationId: 'adminListRankingPolicies',
    auth: 'staff',
    responses: { 200: { description: 'Policies', body: items(rankingPolicyDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/ranking-policies',
    summary: 'Create a draft from the active policy',
    tags,
    operationId: 'adminCreateRankingPolicyDraft',
    auth: 'staff',
    request: { body: rankingPolicyCreateSchema },
    responses: { 201: { description: 'Draft', body: rankingPolicyDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/ranking-policies/{version}',
    summary: 'Get a policy version',
    tags,
    operationId: 'adminGetRankingPolicy',
    auth: 'staff',
    request: { params: versionParams },
    responses: { 200: { description: 'Policy', body: rankingPolicyDtoSchema } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/ranking-policies/{version}',
    summary: 'Edit a draft policy (validated; errors returned)',
    tags,
    operationId: 'adminPatchRankingPolicy',
    auth: 'staff',
    request: { params: versionParams, body: rankingPolicyPatchSchema },
    responses: { 200: { description: 'Policy', body: rankingPolicyDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/ranking-policies/{version}/activate',
    summary: 'Activate a draft and retire the previous active policy',
    tags,
    operationId: 'adminActivateRankingPolicy',
    auth: 'staff',
    request: { params: versionParams, body: rankingPolicyActivateSchema },
    responses: {
      200: { description: 'Policy', body: rankingPolicyDtoSchema },
      400: { description: 'validation_failed: equal or invalid bounds' },
    },
  },
  {
    method: 'get',
    path: '/api/v1/admin/freshness-policies',
    summary: 'List freshness policies',
    tags,
    operationId: 'adminListFreshnessPolicies',
    auth: 'staff',
    responses: { 200: { description: 'Policies' } },
  },
  {
    method: 'put',
    path: '/api/v1/admin/freshness-policies/{dataType}',
    summary: 'Create or update a freshness policy',
    tags,
    operationId: 'adminUpsertFreshnessPolicy',
    auth: 'staff',
    request: { params: z.object({ dataType: z.string() }), body: freshnessPolicyUpsertSchema },
    responses: { 200: { description: 'Policy' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/data-policies',
    summary: 'Data policy settings',
    tags,
    operationId: 'adminListDataPolicies',
    auth: 'staff',
    responses: { 200: { description: 'Settings and rank-eligible evidence count' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/data-policies/{key}',
    summary: 'Update a data policy setting',
    tags,
    operationId: 'adminPatchDataPolicy',
    auth: 'staff',
    request: { params: keyParams, body: dataPolicyPatchSchema },
    responses: { 200: { description: 'Setting' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/feature-flags',
    summary: 'List feature flags',
    tags: platformTags,
    operationId: 'adminListFeatureFlags',
    auth: 'staff',
    responses: { 200: { description: 'Flags' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/feature-flags/{key}',
    summary: 'Toggle a feature flag',
    description:
      'Flags that require review need a reason; regulated flags can only be enabled by typing the key.',
    tags: platformTags,
    operationId: 'adminPatchFeatureFlag',
    auth: 'staff',
    request: { params: keyParams, body: featureFlagPatchSchema },
    responses: { 200: { description: 'Flag' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/settings',
    summary: 'List editable settings',
    tags: platformTags,
    operationId: 'adminListSettings',
    auth: 'staff',
    responses: { 200: { description: 'Settings' } },
  },
  {
    method: 'patch',
    path: '/api/v1/admin/settings/{key}',
    summary: 'Update a setting (typed)',
    tags: platformTags,
    operationId: 'adminPatchSetting',
    auth: 'staff',
    request: { params: keyParams, body: settingPatchSchema },
    responses: { 200: { description: 'Setting' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/staff-roles',
    summary: 'Staff members and roles',
    tags: accessTags,
    operationId: 'adminListStaffRoles',
    auth: 'staff',
    request: { query: staffDirectoryQuerySchema },
    responses: { 200: { description: 'Users with roles' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/staff-roles',
    summary: 'Grant or revoke a staff role',
    tags: accessTags,
    operationId: 'adminChangeStaffRole',
    auth: 'staff',
    request: { body: staffRoleChangeSchema },
    responses: { 200: { description: 'User with roles' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/staff-directory',
    summary: 'Active staff for assignment pickers',
    tags: accessTags,
    operationId: 'adminStaffDirectory',
    auth: 'staff',
    request: { query: staffDirectoryQuerySchema },
    responses: { 200: { description: 'Staff' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/partners',
    summary: 'Partner verification queue',
    tags: accessTags,
    operationId: 'adminListPartners',
    auth: 'staff',
    responses: { 200: { description: 'Partners' } },
  },
  {
    method: 'post',
    path: '/api/v1/admin/partners/{id}/verify',
    summary: 'Verify or reject a partner with the checked scope',
    tags: accessTags,
    operationId: 'adminVerifyPartner',
    auth: 'staff',
    request: { params: idParams, body: partnerVerifySchema },
    responses: { 200: { description: 'Partner' } },
  },
  {
    method: 'get',
    path: '/api/v1/admin/audit',
    summary: 'Audit log (read-only)',
    tags: ['Admin: audit'],
    operationId: 'adminListAudit',
    auth: 'staff',
    request: { query: auditListQuerySchema },
    responses: {
      200: {
        description: 'Audit page',
        body: z.object({ items: z.array(auditEventDtoSchema), nextCursor: z.string().nullable() }),
      },
    },
  },
];

for (const spec of specs) register(spec);

export const adminMarketDataRouteSpecs: readonly RouteSpec[] = specs;
