import { z } from 'zod';
import {
  assignmentDeclineSchema,
  assignmentDtoSchema,
  assignmentListQuerySchema,
  assignmentProposeSchema,
  assignmentRevokeSchema,
  conversationCreateSchema,
  conversationDetailSchema,
  conversationDtoSchema,
  conversationListQuerySchema,
  conversationParticipantAddSchema,
  conversationReadDtoSchema,
  entityNoteCreateSchema,
  entityNoteDtoSchema,
  entityNoteListQuerySchema,
  listRoutes,
  messageCreateSchema,
  messageDtoSchema,
  messageListQuerySchema,
  myAssignmentsQuerySchema,
  myTasksQuerySchema,
  ownerAuthorityDtoSchema,
  ownerAuthorityRejectSchema,
  ownerAuthoritySubmitSchema,
  ownerAuthorityVerifySchema,
  pageOf,
  parcelCreateSchema,
  parcelDtoSchema,
  parcelUpdateSchema,
  propertyArchiveSchema,
  propertyCreateSchema,
  propertyDtoSchema,
  propertyListQuerySchema,
  propertyOverviewSchema,
  propertyUpdateSchema,
  registerRoute,
  taskAssignSchema,
  taskBlockSchema,
  taskCancelSchema,
  taskCompleteSchema,
  taskCreateSchema,
  taskDtoSchema,
  taskListQuerySchema,
  taskUnblockSchema,
  unitCreateSchema,
  unitDtoSchema,
  unitUpdateSchema,
  userIdSchema,
  uuidSchema,
  type RouteSpec,
} from '@simplexd/contracts';

/**
 * OpenAPI registrations for properties, assignments, tasks, notes and
 * conversations. Route handlers import this module for its side effect;
 * registration is idempotent so hot reloads never trip the duplicate guard.
 */

const idParams = z.object({ id: uuidSchema });
const parcelParams = z.object({ id: uuidSchema, parcelId: uuidSchema });
const unitParams = z.object({ id: uuidSchema, unitId: uuidSchema });
const authorityParams = z.object({ id: uuidSchema, authorityId: uuidSchema });
const participantParams = z.object({ id: uuidSchema, userId: userIdSchema });
const items = <T extends z.ZodTypeAny>(item: T) => z.object({ items: z.array(item) });

function register(spec: RouteSpec): void {
  if (listRoutes().some((r) => r.operationId === spec.operationId)) return;
  registerRoute(spec);
}

const notFound = { 404: { description: 'Not visible to the caller' } };

const specs: RouteSpec[] = [
  /* Properties */
  {
    method: 'get',
    path: '/api/v1/properties',
    summary: 'List private properties',
    description:
      'Customers see their active organisation (org.read); staff with customers.read or projects.read_all may scope by organizationId or see all. Filters: kind, marketId, status, q (name or address city).',
    tags: ['properties'],
    operationId: 'listProperties',
    auth: 'session',
    request: { query: propertyListQuerySchema },
    responses: { 200: { description: 'Property page', body: pageOf(propertyDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/properties',
    summary: 'Create a private property',
    description:
      'org.properties.manage in the active organisation, or staff customers.manage / projects.manage naming organizationId. Declared land areas are stored verbatim with a derived m²; plots are never converted. Precise coordinates stay private unless preciseLocationPublic is set.',
    tags: ['properties'],
    operationId: 'createProperty',
    auth: 'session',
    request: { body: propertyCreateSchema },
    responses: { 201: { description: 'Created property', body: propertyDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/properties/{id}',
    summary: 'Read a property',
    tags: ['properties'],
    operationId: 'getProperty',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Property', body: propertyDtoSchema }, ...notFound },
  },
  {
    method: 'patch',
    path: '/api/v1/properties/{id}',
    summary: 'Update a property (optimistic concurrency)',
    tags: ['properties'],
    operationId: 'updateProperty',
    auth: 'session',
    request: { params: idParams, body: propertyUpdateSchema },
    responses: {
      200: { description: 'Updated property', body: propertyDtoSchema },
      409: { description: 'version_conflict when expectedVersion is stale' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/archive',
    summary: 'Archive a property (status semantics, nothing is deleted)',
    tags: ['properties'],
    operationId: 'archiveProperty',
    auth: 'session',
    request: { params: idParams, body: propertyArchiveSchema },
    responses: { 200: { description: 'Archived property', body: propertyDtoSchema }, ...notFound },
  },
  {
    method: 'get',
    path: '/api/v1/properties/{id}/overview',
    summary: 'Property overview read model',
    description:
      'Unit counts and occupancy, parcels, latest owner authority with derived expiry, linked projects and document counts.',
    tags: ['properties'],
    operationId: 'getPropertyOverview',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Overview', body: propertyOverviewSchema }, ...notFound },
  },
  {
    method: 'get',
    path: '/api/v1/properties/{id}/parcels',
    summary: 'List parcels',
    tags: ['properties'],
    operationId: 'listParcels',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Parcels', body: items(parcelDtoSchema) }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/parcels',
    summary: 'Add a parcel (boundary as GeoJSON Polygon coordinates)',
    tags: ['properties'],
    operationId: 'createParcel',
    auth: 'session',
    request: { params: idParams, body: parcelCreateSchema },
    responses: { 201: { description: 'Parcel', body: parcelDtoSchema }, ...notFound },
  },
  {
    method: 'patch',
    path: '/api/v1/properties/{id}/parcels/{parcelId}',
    summary: 'Update a parcel',
    tags: ['properties'],
    operationId: 'updateParcel',
    auth: 'session',
    request: { params: parcelParams, body: parcelUpdateSchema },
    responses: { 200: { description: 'Parcel', body: parcelDtoSchema }, ...notFound },
  },
  {
    method: 'delete',
    path: '/api/v1/properties/{id}/parcels/{parcelId}',
    summary: 'Delete a parcel',
    tags: ['properties'],
    operationId: 'deleteParcel',
    auth: 'session',
    request: { params: parcelParams },
    responses: { 204: { description: 'Deleted' }, ...notFound },
  },
  {
    method: 'get',
    path: '/api/v1/properties/{id}/units',
    summary: 'List units',
    tags: ['properties'],
    operationId: 'listUnits',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Units', body: items(unitDtoSchema) }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/units',
    summary: 'Add a unit (label unique per property)',
    tags: ['properties'],
    operationId: 'createUnit',
    auth: 'session',
    request: { params: idParams, body: unitCreateSchema },
    responses: {
      201: { description: 'Unit', body: unitDtoSchema },
      409: { description: 'Duplicate label' },
      ...notFound,
    },
  },
  {
    method: 'patch',
    path: '/api/v1/properties/{id}/units/{unitId}',
    summary: 'Update a unit',
    tags: ['properties'],
    operationId: 'updateUnit',
    auth: 'session',
    request: { params: unitParams, body: unitUpdateSchema },
    responses: { 200: { description: 'Unit', body: unitDtoSchema }, ...notFound },
  },
  {
    method: 'delete',
    path: '/api/v1/properties/{id}/units/{unitId}',
    summary: 'Delete a unit (refused with 409 when leases reference it)',
    tags: ['properties'],
    operationId: 'deleteUnit',
    auth: 'session',
    request: { params: unitParams },
    responses: {
      204: { description: 'Deleted' },
      409: { description: 'Referenced by other records' },
      ...notFound,
    },
  },
  {
    method: 'get',
    path: '/api/v1/properties/{id}/owner-authorities',
    summary: 'List owner authorities',
    tags: ['properties'],
    operationId: 'listOwnerAuthorities',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Authorities', body: items(ownerAuthorityDtoSchema) },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/owner-authorities',
    summary: 'Submit an owner authority document',
    description:
      'The document must be a file of the same organisation that is neither quarantined nor rejected.',
    tags: ['properties'],
    operationId: 'submitOwnerAuthority',
    auth: 'session',
    request: { params: idParams, body: ownerAuthoritySubmitSchema },
    responses: {
      201: { description: 'Pending authority', body: ownerAuthorityDtoSchema },
      422: { description: 'file_rejected' },
      423: { description: 'file_quarantined' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/owner-authorities/{authorityId}/verify',
    summary: 'Verify an owner authority (staff, rentals.manage)',
    tags: ['properties'],
    operationId: 'verifyOwnerAuthority',
    auth: 'staff',
    request: { params: authorityParams, body: ownerAuthorityVerifySchema },
    responses: {
      200: { description: 'Verified authority', body: ownerAuthorityDtoSchema },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/properties/{id}/owner-authorities/{authorityId}/reject',
    summary: 'Reject an owner authority (staff, rentals.manage)',
    tags: ['properties'],
    operationId: 'rejectOwnerAuthority',
    auth: 'staff',
    request: { params: authorityParams, body: ownerAuthorityRejectSchema },
    responses: {
      200: { description: 'Rejected authority', body: ownerAuthorityDtoSchema },
      ...notFound,
    },
  },
  /* Assignments */
  {
    method: 'get',
    path: '/api/v1/assignments',
    summary: 'Assignments on a service request or project',
    description:
      'Staff see all; customers see accepted, active and completed assignments on their own entities; partners see their own.',
    tags: ['assignments'],
    operationId: 'listAssignments',
    auth: 'session',
    request: { query: assignmentListQuerySchema },
    responses: {
      200: { description: 'Assignment page', body: pageOf(assignmentDtoSchema) },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/assignments',
    summary: 'Propose an assignment',
    description:
      'Staff with service_requests.assign or projects.manage (project managers only on their own work). The assignee must be staff or a registered partner.',
    tags: ['assignments'],
    operationId: 'proposeAssignment',
    auth: 'staff',
    request: { body: assignmentProposeSchema },
    responses: {
      201: { description: 'Proposed assignment', body: assignmentDtoSchema },
      409: { description: 'Open assignment already exists' },
    },
  },
  {
    method: 'get',
    path: '/api/v1/assignments/mine',
    summary: 'My assignments',
    tags: ['assignments'],
    operationId: 'listMyAssignments',
    auth: 'session',
    request: { query: myAssignmentsQuerySchema },
    responses: { 200: { description: 'Assignment page', body: pageOf(assignmentDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/assignments/{id}',
    summary: 'Read an assignment',
    tags: ['assignments'],
    operationId: 'getAssignment',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Assignment', body: assignmentDtoSchema }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/assignments/{id}/accept',
    summary: 'Accept a proposed assignment (assignee only)',
    tags: ['assignments'],
    operationId: 'acceptAssignment',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Accepted assignment', body: assignmentDtoSchema },
      409: { description: 'invalid_transition' },
    },
  },
  {
    method: 'post',
    path: '/api/v1/assignments/{id}/decline',
    summary: 'Decline a proposed assignment (assignee only)',
    tags: ['assignments'],
    operationId: 'declineAssignment',
    auth: 'session',
    request: { params: idParams, body: assignmentDeclineSchema },
    responses: {
      200: { description: 'Declined assignment', body: assignmentDtoSchema },
      409: { description: 'invalid_transition' },
    },
  },
  {
    method: 'post',
    path: '/api/v1/assignments/{id}/activate',
    summary: 'Activate an accepted assignment (staff)',
    tags: ['assignments'],
    operationId: 'activateAssignment',
    auth: 'staff',
    request: { params: idParams },
    responses: {
      200: { description: 'Active assignment', body: assignmentDtoSchema },
      409: { description: 'invalid_transition' },
    },
  },
  {
    method: 'post',
    path: '/api/v1/assignments/{id}/complete',
    summary: 'Complete an active assignment (staff or the assignee)',
    tags: ['assignments'],
    operationId: 'completeAssignment',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Completed assignment', body: assignmentDtoSchema },
      409: { description: 'invalid_transition' },
    },
  },
  {
    method: 'post',
    path: '/api/v1/assignments/{id}/revoke',
    summary: 'Revoke an assignment with a reason (staff); access ends immediately',
    tags: ['assignments'],
    operationId: 'revokeAssignment',
    auth: 'staff',
    request: { params: idParams, body: assignmentRevokeSchema },
    responses: {
      200: { description: 'Revoked assignment', body: assignmentDtoSchema },
      409: { description: 'invalid_transition' },
    },
  },
  /* Tasks */
  {
    method: 'get',
    path: '/api/v1/tasks',
    summary: 'Tasks on a service request, project or assignment',
    description:
      'internal tasks are never returned to customers or partners; customer tasks go to the organisation; partner tasks to assignees; all to everyone with access.',
    tags: ['tasks'],
    operationId: 'listTasks',
    auth: 'session',
    request: { query: taskListQuerySchema },
    responses: { 200: { description: 'Task page', body: pageOf(taskDtoSchema) }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/tasks',
    summary: 'Create a task (staff)',
    tags: ['tasks'],
    operationId: 'createTask',
    auth: 'staff',
    request: { body: taskCreateSchema },
    responses: { 201: { description: 'Task', body: taskDtoSchema }, ...notFound },
  },
  {
    method: 'get',
    path: '/api/v1/tasks/mine',
    summary: 'My tasks',
    description:
      "Customers: open tasks awaiting their organisation's action plus anything assigned to them; staff and partners: open tasks assigned to them.",
    tags: ['tasks'],
    operationId: 'listMyTasks',
    auth: 'session',
    request: { query: myTasksQuerySchema },
    responses: { 200: { description: 'Task page', body: pageOf(taskDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/tasks/{id}',
    summary: 'Read a task',
    tags: ['tasks'],
    operationId: 'getTask',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Task', body: taskDtoSchema }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/tasks/{id}/assign',
    summary: 'Assign or unassign a task (staff)',
    tags: ['tasks'],
    operationId: 'assignTask',
    auth: 'staff',
    request: { params: idParams, body: taskAssignSchema },
    responses: { 200: { description: 'Task', body: taskDtoSchema }, ...notFound },
  },
  {
    method: 'post',
    path: '/api/v1/tasks/{id}/complete',
    summary:
      'Complete a task (assignee, staff, or the customer organisation for customer-action tasks)',
    tags: ['tasks'],
    operationId: 'completeTask',
    auth: 'session',
    request: { params: idParams, body: taskCompleteSchema },
    responses: {
      200: { description: 'Task', body: taskDtoSchema },
      409: { description: 'invalid_transition' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/tasks/{id}/block',
    summary: 'Block a task with a reason (assignee or staff)',
    tags: ['tasks'],
    operationId: 'blockTask',
    auth: 'session',
    request: { params: idParams, body: taskBlockSchema },
    responses: {
      200: { description: 'Task', body: taskDtoSchema },
      409: { description: 'invalid_transition' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/tasks/{id}/unblock',
    summary: 'Unblock a task (assignee or staff)',
    tags: ['tasks'],
    operationId: 'unblockTask',
    auth: 'session',
    request: { params: idParams, body: taskUnblockSchema },
    responses: {
      200: { description: 'Task', body: taskDtoSchema },
      409: { description: 'invalid_transition' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/tasks/{id}/cancel',
    summary: 'Cancel a task with a reason (staff)',
    tags: ['tasks'],
    operationId: 'cancelTask',
    auth: 'staff',
    request: { params: idParams, body: taskCancelSchema },
    responses: {
      200: { description: 'Task', body: taskDtoSchema },
      409: { description: 'invalid_transition' },
      ...notFound,
    },
  },
  /* Notes */
  {
    method: 'get',
    path: '/api/v1/notes',
    summary: 'Notes on an entity the caller may see',
    description:
      'Visibility is derived from the parent entity: staff see all; customers customer/all; partners partner/all on assigned entities. Notes are append-only.',
    tags: ['notes'],
    operationId: 'listEntityNotes',
    auth: 'session',
    request: { query: entityNoteListQuerySchema },
    responses: {
      200: { description: 'Note page', body: pageOf(entityNoteDtoSchema) },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/notes',
    summary: 'Append a note with an explicit visibility',
    tags: ['notes'],
    operationId: 'createEntityNote',
    auth: 'session',
    request: { body: entityNoteCreateSchema },
    responses: {
      201: { description: 'Note', body: entityNoteDtoSchema },
      403: { description: 'Visibility not allowed for the caller' },
      ...notFound,
    },
  },
  /* Conversations */
  {
    method: 'get',
    path: '/api/v1/conversations',
    summary: 'My conversations',
    tags: ['conversations'],
    operationId: 'listConversations',
    auth: 'session',
    request: { query: conversationListQuerySchema },
    responses: { 200: { description: 'Conversation page', body: pageOf(conversationDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/conversations',
    summary: 'Start a conversation',
    description:
      'Participants must already have access to the linked entity or organisation (members, staff, assigned partners). Internal conversations are staff only.',
    tags: ['conversations'],
    operationId: 'createConversation',
    auth: 'session',
    request: { body: conversationCreateSchema },
    responses: {
      201: { description: 'Conversation', body: conversationDetailSchema },
      ...notFound,
    },
  },
  {
    method: 'get',
    path: '/api/v1/conversations/{id}',
    summary: 'Conversation detail with participants',
    description:
      'Non-participants receive not_found even with a valid id; staff observers need messages.read_all.',
    tags: ['conversations'],
    operationId: 'getConversation',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Conversation', body: conversationDetailSchema },
      ...notFound,
    },
  },
  {
    method: 'get',
    path: '/api/v1/conversations/{id}/messages',
    summary: 'Messages, newest first, cursor paginated',
    tags: ['conversations'],
    operationId: 'listMessages',
    auth: 'session',
    request: { params: idParams, query: messageListQuerySchema },
    responses: {
      200: { description: 'Message page', body: pageOf(messageDtoSchema) },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/conversations/{id}/messages',
    summary: 'Post a message',
    description:
      'Participants with org.messages.send, tenant.messages.send, a partner account or a staff role. internalOnly is staff only. Attachments must be usable files the sender can access.',
    tags: ['conversations'],
    operationId: 'postMessage',
    auth: 'session',
    request: { params: idParams, body: messageCreateSchema },
    responses: {
      201: { description: 'Message', body: messageDtoSchema },
      409: { description: 'Conversation closed' },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/conversations/{id}/read',
    summary: 'Mark the conversation read',
    tags: ['conversations'],
    operationId: 'markConversationRead',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Read marker', body: conversationReadDtoSchema },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/conversations/{id}/participants',
    summary: 'Add a participant (staff or the creator)',
    tags: ['conversations'],
    operationId: 'addConversationParticipant',
    auth: 'session',
    request: { params: idParams, body: conversationParticipantAddSchema },
    responses: {
      201: { description: 'Conversation', body: conversationDetailSchema },
      ...notFound,
    },
  },
  {
    method: 'delete',
    path: '/api/v1/conversations/{id}/participants/{userId}',
    summary: 'Remove a participant (staff or the creator) or leave',
    tags: ['conversations'],
    operationId: 'removeConversationParticipant',
    auth: 'session',
    request: { params: participantParams },
    responses: {
      200: { description: 'Conversation', body: conversationDetailSchema },
      ...notFound,
    },
  },
  {
    method: 'post',
    path: '/api/v1/conversations/{id}/close',
    summary: 'Close a conversation (staff or the creator)',
    tags: ['conversations'],
    operationId: 'closeConversation',
    auth: 'session',
    request: { params: idParams },
    responses: {
      200: { description: 'Conversation', body: conversationDetailSchema },
      ...notFound,
    },
  },
];

for (const spec of specs) register(spec);

export const collaborationRouteSpecs: readonly RouteSpec[] = specs;
