import { z } from 'zod';
import {
  awardDecideSchema,
  awardDtoSchema,
  awardOutcomeDtoSchema,
  awardPublishSchema,
  awardRespondSchema,
  bidDisqualifySchema,
  bidDtoSchema,
  bidEvaluationDtoSchema,
  bidEvaluationInputSchema,
  bidReadDtoSchema,
  bidRevisionInputSchema,
  bidSubmitSchema,
  bidWithdrawSchema,
  bidsOpenSchema,
  deliveryDtoSchema,
  deliveryListQuerySchema,
  deliveryRecordSchema,
  discrepancyCreateSchema,
  discrepancyDtoSchema,
  discrepancyTransitionSchema,
  invitedTenderDtoSchema,
  listRoutes,
  pageOf,
  partnerAwardListQuerySchema,
  partnerBidListQuerySchema,
  partnerTenderListQuerySchema,
  purchaseOrderAcknowledgeSchema,
  purchaseOrderCancelSchema,
  purchaseOrderCreateSchema,
  purchaseOrderDetailSchema,
  purchaseOrderDtoSchema,
  purchaseOrderIssueSchema,
  purchaseOrderListQuerySchema,
  registerRoute,
  rfqCancelSchema,
  rfqComparisonDtoSchema,
  rfqCreateSchema,
  rfqDetailSchema,
  rfqDtoSchema,
  rfqInviteSchema,
  rfqIssueSchema,
  rfqItemsReplaceSchema,
  rfqListQuerySchema,
  rfqPatchSchema,
  rfqResponseDtoSchema,
  rfqResponseSubmitSchema,
  supplierDirectoryQuerySchema,
  supplierDirectoryResponseSchema,
  tenderCancelSchema,
  tenderCloseSchema,
  tenderComparisonDtoSchema,
  tenderCreateSchema,
  tenderDetailSchema,
  tenderDraftPatchSchema,
  tenderDtoSchema,
  tenderEvaluateStartSchema,
  tenderInvitationDtoSchema,
  tenderInvitationRespondSchema,
  tenderInviteSchema,
  tenderListQuerySchema,
  tenderPublishSchema,
  tenderQuestionAnswerSchema,
  tenderQuestionAskSchema,
  tenderQuestionDtoSchema,
  tenderRevisionCreateSchema,
  tenderVariationSchema,
  uuidSchema,
  type RouteSpec,
} from '@simplexd/contracts';

/**
 * OpenAPI registrations for contractor tendering (sealed bids) and materials
 * procurement. Both modules are expansion features: every endpoint answers
 * 404 feature_disabled unless `expansion.contractor_tendering` /
 * `expansion.materials_procurement` is enabled for the caller. Registration
 * is idempotent so hot reloads never trip the duplicate-operation guard.
 */

export const commercialIdParams = z.object({ id: uuidSchema });
export const tenderQuestionParams = z.object({ id: uuidSchema, qid: uuidSchema });
export const rfqResponseParams = z.object({ id: uuidSchema, rid: uuidSchema });
export const discrepancyParams = z.object({ id: uuidSchema, did: uuidSchema });

function ensure(spec: RouteSpec): RouteSpec {
  const existing = listRoutes().find((r) => r.operationId === spec.operationId);
  return existing ?? registerRoute(spec);
}

const tenderTags = ['Tenders'];
const bidTags = ['Bids'];
const procurementTags = ['Procurement'];
const FEATURE_TENDERS = 'Feature flag: expansion.contractor_tendering.';
const FEATURE_PROCUREMENT = 'Feature flag: expansion.materials_procurement.';
const items = (item: z.ZodTypeAny) => z.object({ items: z.array(item) });

const specs: RouteSpec[] = [
  /* ---------------------------------- tenders ---------------------------------- */
  {
    method: 'get',
    path: '/api/v1/tenders',
    summary: 'List tenders',
    description: `Staff (tenders.manage) list every tender; customers (org.read) their organisation's. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.list',
    auth: 'session',
    request: { query: tenderListQuerySchema },
    responses: { 200: { description: 'Tender page', body: pageOf(tenderDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders',
    summary: 'Create a draft tender',
    description: `tenders.manage. Timeline validated by the bidding timeline engine; weights must sum to 100 or 1.0. Reference TND-YYYY-NNNN. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.create',
    auth: 'staff',
    request: { body: tenderCreateSchema },
    responses: { 201: { description: 'Draft tender', body: tenderDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/mine',
    summary: 'Partner workspace: invited tenders',
    description: `partner.tenders.view_invited. Timeline in the tender's display zone and UTC. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.mine',
    auth: 'partner',
    request: { query: partnerTenderListQuerySchema },
    responses: { 200: { description: 'Invited tenders', body: pageOf(invitedTenderDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/mine/awards',
    summary: 'Partner workspace: award outcomes',
    description: `Published awards only; unsuccessful bidders see their outcome without the winner's details. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.mine.awards',
    auth: 'partner',
    request: { query: partnerAwardListQuerySchema },
    responses: { 200: { description: 'Award outcomes', body: pageOf(awardOutcomeDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}',
    summary: 'Tender detail',
    description: `Staff, customers of the organisation, or invited partners (marks the invitation viewed). ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Tender detail', body: tenderDetailSchema } },
  },
  {
    method: 'patch',
    path: '/api/v1/tenders/{id}',
    summary: 'Edit a draft tender',
    description: `tenders.manage; drafts only, optimistic concurrency via expectedVersion. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.updateDraft',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderDraftPatchSchema },
    responses: { 200: { description: 'Tender', body: tenderDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/publish',
    summary: 'Publish a tender',
    description: `tenders.manage; draft → published, deadline must be in the future; invitees notified via outbox. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.publish',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderPublishSchema },
    responses: { 200: { description: 'Tender', body: tenderDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/revisions',
    summary: 'Revise a published tender (addendum, deadline extension)',
    description: `tenders.manage; append-only tender_revisions row; deadlines only ever extend. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.revise',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderRevisionCreateSchema },
    responses: { 200: { description: 'Tender detail', body: tenderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/variations',
    summary: 'Record a post-award variation',
    description: `tenders.manage; awarded tenders only; append-only revision with reason. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.variation',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderVariationSchema },
    responses: { 200: { description: 'Tender detail', body: tenderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/close',
    summary: 'Close a tender manually',
    description: `tenders.manage; only once the database clock has passed the effective deadline. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.close',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderCloseSchema },
    responses: { 200: { description: 'Tender', body: tenderDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/cancel',
    summary: 'Cancel a tender',
    description: `tenders.manage; reason required. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.cancel',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderCancelSchema },
    responses: { 200: { description: 'Tender', body: tenderDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}/invitations',
    summary: 'List invitations',
    description: `Staff and customers see all; a partner sees only their own. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.invitations.list',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Invitations', body: items(tenderInvitationDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/invitations',
    summary: 'Invite partner users',
    description: `tenders.manage; invitees need a partner profile. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.invitations.create',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderInviteSchema },
    responses: { 200: { description: 'Invitations', body: items(tenderInvitationDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/invitations/respond',
    summary: 'Accept or decline an invitation',
    description: `Invited partner. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.invitations.respond',
    auth: 'partner',
    request: { params: commercialIdParams, body: tenderInvitationRespondSchema },
    responses: { 200: { description: 'Invitation', body: tenderInvitationDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}/questions',
    summary: 'List clarification questions',
    description: `Staff: all with asker; partners: own plus published (anonymised); customers: published. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.questions.list',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Questions', body: items(tenderQuestionDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/questions',
    summary: 'Ask a clarification question',
    description: `Invited partner, before the question cutoff (database clock). ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.questions.ask',
    auth: 'partner',
    request: { params: commercialIdParams, body: tenderQuestionAskSchema },
    responses: { 201: { description: 'Question', body: tenderQuestionDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/questions/{qid}/answer',
    summary: 'Answer a question (optionally publish)',
    description: `tenders.manage. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.questions.answer',
    auth: 'staff',
    request: { params: tenderQuestionParams, body: tenderQuestionAnswerSchema },
    responses: { 200: { description: 'Question', body: tenderQuestionDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/questions/{qid}/publish',
    summary: 'Publish an answer to every invitee (anonymised)',
    description: `tenders.manage. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.questions.publish',
    auth: 'staff',
    request: { params: tenderQuestionParams },
    responses: { 200: { description: 'Question', body: tenderQuestionDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}/bids',
    summary: 'List bids with the sealing rule',
    description: `Partner: own bid only. Staff: existence/partner/submittedAt until opened, then content (access logged). Customers: nothing until closed and opened. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'tenders.bids.list',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Bids', body: items(bidReadDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/bids',
    summary: 'Create (or return) the partner draft bid',
    description: `partner.bids.submit; before the deadline. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'tenders.bids.create',
    auth: 'partner',
    request: { params: commercialIdParams },
    responses: { 201: { description: 'Bid', body: bidDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/open-bids',
    summary: 'Open the sealed bids (audited)',
    description: `bids.open_sealed (MFA); tender must be closed; writes bid_access_log rows. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'tenders.bids.open',
    auth: 'staff',
    request: { params: commercialIdParams, body: bidsOpenSchema },
    responses: { 200: { description: 'Opened bids', body: items(bidReadDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/evaluate',
    summary: 'Start evaluation (closed → evaluating)',
    description: `bids.evaluate; opens sealed bids if not yet opened, which requires bids.open_sealed on the same actor. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'tenders.evaluate.start',
    auth: 'staff',
    request: { params: commercialIdParams, body: tenderEvaluateStartSchema },
    responses: { 200: { description: 'Evaluation started' } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}/evaluation',
    summary: 'Comparison read model',
    description: `bids.evaluate; opened bids with amounts, evaluator scores, mean weighted score and rank (access logged). ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'tenders.evaluation.get',
    auth: 'staff',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Comparison', body: tenderComparisonDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/tenders/{id}/award',
    summary: 'Read the award',
    description: `Staff any time; customers once published; partners once published (winner: award, others: unsuccessful outcome only), else 404. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.award.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Award or outcome', body: z.union([awardDtoSchema, awardOutcomeDtoSchema]) } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/award',
    summary: 'Decide the award',
    description: `tenders.manage; evaluating tender, evaluated bid; contract value from the winning revision. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.award.decide',
    auth: 'staff',
    request: { params: commercialIdParams, body: awardDecideSchema },
    responses: { 201: { description: 'Award', body: awardDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/award/publish',
    summary: 'Publish the award',
    description: `tenders.manage; tender → awarded, winning bid → awarded, other evaluated bids → unsuccessful; partners notified. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.award.publish',
    auth: 'staff',
    request: { params: commercialIdParams, body: awardPublishSchema },
    responses: { 200: { description: 'Award', body: awardDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/tenders/{id}/award/respond',
    summary: 'Winner accepts or declines the award',
    description: `Awarded partner. ${FEATURE_TENDERS}`,
    tags: tenderTags,
    operationId: 'tenders.award.respond',
    auth: 'partner',
    request: { params: commercialIdParams, body: awardRespondSchema },
    responses: { 200: { description: 'Award', body: awardDtoSchema } },
  },
  /* ----------------------------------- bids ------------------------------------ */
  {
    method: 'get',
    path: '/api/v1/bids/mine',
    summary: 'Partner workspace: my bids',
    description: `Strictly the caller's own bids. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.mine',
    auth: 'partner',
    request: { query: partnerBidListQuerySchema },
    responses: { 200: { description: 'Bids', body: pageOf(bidDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/bids/{id}',
    summary: 'Read a bid',
    description: `Partner: own bid. Staff: sealed summary until opened, then content (logged). Customer: only after close and opening (logged). ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Bid', body: bidReadDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/bids/{id}/revisions',
    summary: 'Add unsubmitted bid content',
    description: `partner.bids.submit; before the deadline; attachments must be the partner's own files. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.revisions.create',
    auth: 'partner',
    request: { params: commercialIdParams, body: bidRevisionInputSchema },
    responses: { 200: { description: 'Bid', body: bidDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/bids/{id}/submit',
    summary: 'Submit (or re-submit) a bid',
    description: `partner.bids.submit; the deadline is checked inside the transaction on the database clock; after it every submit fails with deadline_passed. Idempotent. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.submit',
    auth: 'partner',
    idempotent: true,
    request: { params: commercialIdParams, body: bidSubmitSchema },
    responses: { 200: { description: 'Bid', body: bidDtoSchema }, 409: { description: 'deadline_passed / version_conflict' } },
  },
  {
    method: 'post',
    path: '/api/v1/bids/{id}/withdraw',
    summary: 'Withdraw a bid before the deadline',
    description: `partner.bids.submit; reason required. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.withdraw',
    auth: 'partner',
    request: { params: commercialIdParams, body: bidWithdrawSchema },
    responses: { 200: { description: 'Bid', body: bidDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/bids/{id}/evaluations',
    summary: 'Score a bid per criterion (0-100)',
    description: `bids.evaluate; one row per evaluator per bid; weighted score computed from the tender weights. ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.evaluations.create',
    auth: 'staff',
    request: { params: commercialIdParams, body: bidEvaluationInputSchema },
    responses: { 200: { description: 'Evaluation', body: bidEvaluationDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/bids/{id}/disqualify',
    summary: 'Disqualify a bid',
    description: `bids.evaluate; reason required (audited). ${FEATURE_TENDERS}`,
    tags: bidTags,
    operationId: 'bids.disqualify',
    auth: 'staff',
    request: { params: commercialIdParams, body: bidDisqualifySchema },
    responses: { 200: { description: 'Disqualified' } },
  },
  /* ----------------------------------- RFQs ------------------------------------ */
  {
    method: 'get',
    path: '/api/v1/rfqs/supplier-directory',
    summary: 'Supplier directory',
    description: `procurement.manage; facilities and coverage with the evidence labels the seed carries; prices only from supplier_quotes. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.supplierDirectory',
    auth: 'staff',
    request: { query: supplierDirectoryQuerySchema },
    responses: { 200: { description: 'Directory', body: supplierDirectoryResponseSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/rfqs',
    summary: 'List RFQs',
    description: `Staff all; customers their organisation's; suppliers those naming them. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.list',
    auth: 'session',
    request: { query: rfqListQuerySchema },
    responses: { 200: { description: 'RFQs', body: pageOf(rfqDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs',
    summary: 'Create a draft RFQ with items',
    description: `procurement.manage. Reference RFQ-YYYY-NNNN. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.create',
    auth: 'staff',
    request: { body: rfqCreateSchema },
    responses: { 201: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/rfqs/{id}',
    summary: 'RFQ detail',
    description: `Suppliers see only their own response. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'patch',
    path: '/api/v1/rfqs/{id}',
    summary: 'Edit a draft RFQ',
    description: `procurement.manage. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.update',
    auth: 'staff',
    request: { params: commercialIdParams, body: rfqPatchSchema },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'put',
    path: '/api/v1/rfqs/{id}/items',
    summary: 'Replace the items of a draft RFQ',
    description: `procurement.manage. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.items.replace',
    auth: 'staff',
    request: { params: commercialIdParams, body: rfqItemsReplaceSchema },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/issue',
    summary: 'Issue an RFQ (draft → sent) with a deadline',
    description: `procurement.manage; optionally invites supplier users. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.issue',
    auth: 'staff',
    request: { params: commercialIdParams, body: rfqIssueSchema },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/invite',
    summary: 'Invite supplier users',
    description: `procurement.manage; suppliers need a partner profile. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.invite',
    auth: 'staff',
    request: { params: commercialIdParams, body: rfqInviteSchema },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/close',
    summary: 'Close an RFQ',
    description: `procurement.manage. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.close',
    auth: 'staff',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/cancel',
    summary: 'Cancel an RFQ',
    description: `procurement.manage; reason required. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.cancel',
    auth: 'staff',
    request: { params: commercialIdParams, body: rfqCancelSchema },
    responses: { 200: { description: 'RFQ', body: rfqDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/responses',
    summary: 'Submit a response',
    description: `Supplier (partner.rfqs.respond, before the deadline) or staff on behalf of an invited supplier / manual supplierName. Lines carry unitPriceKobo, quantityUnit and an optional declared conversion. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.responses.submit',
    auth: 'session',
    request: { params: commercialIdParams, body: rfqResponseSubmitSchema },
    responses: { 201: { description: 'Response', body: rfqResponseDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/rfqs/{id}/responses/{rid}/withdraw',
    summary: 'Withdraw a response',
    description: `Supplier (own) or staff. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.responses.withdraw',
    auth: 'session',
    request: { params: rfqResponseParams },
    responses: { 200: { description: 'Response', body: rfqResponseDtoSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/rfqs/{id}/comparison',
    summary: 'Delivered-cost comparison',
    description: `Staff and customers. Lines in other units are converted only through declared factors; unknown conversions are reported as unit_conversion_unknown and keep the total unknown. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'rfqs.comparison',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Comparison', body: rfqComparisonDtoSchema } },
  },
  /* ------------------------------ purchase orders ------------------------------ */
  {
    method: 'get',
    path: '/api/v1/purchase-orders',
    summary: 'List purchase orders',
    description: `Staff all; customers their organisation's; vendors those naming them. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.list',
    auth: 'session',
    request: { query: purchaseOrderListQuerySchema },
    responses: { 200: { description: 'Purchase orders', body: pageOf(purchaseOrderDtoSchema) } },
  },
  {
    method: 'post',
    path: '/api/v1/purchase-orders',
    summary: 'Create a purchase order from a response',
    description: `procurement.manage; lines copied, totals computed server-side; unknown conversions must be declared (staff_measured) first. Number PO-YYYY-NNNN. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.create',
    auth: 'staff',
    request: { body: purchaseOrderCreateSchema },
    responses: { 201: { description: 'Purchase order', body: purchaseOrderDetailSchema } },
  },
  {
    method: 'get',
    path: '/api/v1/purchase-orders/{id}',
    summary: 'Purchase order detail with delivery progress',
    description: FEATURE_PROCUREMENT,
    tags: procurementTags,
    operationId: 'purchaseOrders.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Purchase order', body: purchaseOrderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/purchase-orders/{id}/issue',
    summary: 'Issue a purchase order',
    description: `procurement.manage; idempotent; marks the response selected and the RFQ awarded. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.issue',
    auth: 'staff',
    idempotent: true,
    request: { params: commercialIdParams, body: purchaseOrderIssueSchema },
    responses: { 200: { description: 'Purchase order', body: purchaseOrderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/purchase-orders/{id}/acknowledge',
    summary: 'Supplier acknowledges an issued order',
    description: `Supplier named on the order (partner.rfqs.respond) or staff. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.acknowledge',
    auth: 'session',
    request: { params: commercialIdParams, body: purchaseOrderAcknowledgeSchema },
    responses: { 200: { description: 'Purchase order', body: purchaseOrderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/purchase-orders/{id}/cancel',
    summary: 'Cancel a purchase order',
    description: `procurement.manage; reason required. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.cancel',
    auth: 'staff',
    request: { params: commercialIdParams, body: purchaseOrderCancelSchema },
    responses: { 200: { description: 'Purchase order', body: purchaseOrderDetailSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/purchase-orders/{id}/deliveries',
    summary: 'Record a delivery',
    description: `procurement.manage; received quantities per line, evidence files of the organisation, deliveredAt and receiver. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'purchaseOrders.deliveries.record',
    auth: 'staff',
    request: { params: commercialIdParams, body: deliveryRecordSchema },
    responses: { 201: { description: 'Delivery', body: deliveryDtoSchema } },
  },
  /* -------------------------------- deliveries --------------------------------- */
  {
    method: 'get',
    path: '/api/v1/deliveries',
    summary: 'List deliveries',
    description: `Staff all; customers their organisation's; vendors (partner.deliveries.view) those on orders naming them. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'deliveries.list',
    auth: 'session',
    request: { query: deliveryListQuerySchema },
    responses: { 200: { description: 'Deliveries', body: pageOf(deliveryDtoSchema) } },
  },
  {
    method: 'get',
    path: '/api/v1/deliveries/{id}',
    summary: 'Delivery detail with discrepancies',
    description: FEATURE_PROCUREMENT,
    tags: procurementTags,
    operationId: 'deliveries.get',
    auth: 'session',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Delivery', body: deliveryDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/deliveries/{id}/accept',
    summary: 'Accept a delivery',
    description: `procurement.manage; no open discrepancies. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'deliveries.accept',
    auth: 'staff',
    request: { params: commercialIdParams },
    responses: { 200: { description: 'Delivery', body: deliveryDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/deliveries/{id}/discrepancies',
    summary: 'Open a discrepancy',
    description: `procurement.manage; short delivery, damaged, wrong spec or other with quantity; supplier notified via outbox. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'deliveries.discrepancies.create',
    auth: 'staff',
    request: { params: commercialIdParams, body: discrepancyCreateSchema },
    responses: { 201: { description: 'Discrepancy', body: discrepancyDtoSchema } },
  },
  {
    method: 'post',
    path: '/api/v1/deliveries/{id}/discrepancies/{did}/transition',
    summary: 'Move a discrepancy (open → supplier_notified → resolved | credited | returned)',
    description: `procurement.manage; resolution text required to close. ${FEATURE_PROCUREMENT}`,
    tags: procurementTags,
    operationId: 'deliveries.discrepancies.transition',
    auth: 'staff',
    request: { params: discrepancyParams, body: discrepancyTransitionSchema },
    responses: { 200: { description: 'Discrepancy', body: discrepancyDtoSchema } },
  },
];

for (const spec of specs) ensure(spec);

export const commercialRouteCount = specs.length;
