import { z } from 'zod';
import {
  contentListQuerySchema,
  contentPageCreateSchema,
  contentPageDetailSchema,
  contentPageDtoSchema,
  contentPagePatchSchema,
  contentPreviewRenderSchema,
  contentPublishActionSchema,
  contentRevisionCreateSchema,
  contentRevisionDtoSchema,
  leadConvertResultSchema,
  leadConvertSchema,
  leadDetailDtoSchema,
  leadDtoSchema,
  leadListQuerySchema,
  leadNoteCreateSchema,
  leadUpdateSchema,
  contentMediaListResponseSchema,
  noteDtoSchema,
  pageOf,
  redirectDtoSchema,
  redirectPatchSchema,
  redirectUpsertSchema,
  registerRoute,
  staffAssigneeDtoSchema,
  uuidSchema,
} from '@simplexd/contracts';

/** OpenAPI registrations for CMS and CRM administration endpoints. */

const idParam = z.object({ id: uuidSchema });

export const contentCrmRoutes = [
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/content/pages',
    summary: 'List content pages',
    tags: ['Admin: content'],
    operationId: 'adminListContentPages',
    auth: 'staff',
    request: { query: contentListQuerySchema },
    responses: {
      200: { description: 'Page of content pages', body: pageOf(contentPageDtoSchema) },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/content/pages',
    summary: 'Create a draft page with revision 1',
    tags: ['Admin: content'],
    operationId: 'adminCreateContentPage',
    auth: 'staff',
    request: { body: contentPageCreateSchema },
    responses: { 201: { description: 'Created', body: contentPageDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/content/pages/{id}',
    summary: 'Page detail with revisions',
    tags: ['Admin: content'],
    operationId: 'adminGetContentPage',
    auth: 'staff',
    request: { params: idParam },
    responses: { 200: { description: 'Detail', body: contentPageDetailSchema } },
  }),
  registerRoute({
    method: 'patch',
    path: '/api/v1/admin/content/pages/{id}',
    summary: 'Update SEO and ordering (expectedVersion)',
    tags: ['Admin: content'],
    operationId: 'adminPatchContentPage',
    auth: 'staff',
    request: { params: idParam, body: contentPagePatchSchema },
    responses: { 200: { description: 'Updated', body: contentPageDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/content/pages/{id}/revisions',
    summary: 'Revision history',
    tags: ['Admin: content'],
    operationId: 'adminListContentRevisions',
    auth: 'staff',
    request: { params: idParam },
    responses: {
      200: {
        description: 'Revisions',
        body: z.object({ items: z.array(contentRevisionDtoSchema) }),
      },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/content/pages/{id}/revisions',
    summary: 'Save a new draft revision',
    tags: ['Admin: content'],
    operationId: 'adminCreateContentRevision',
    auth: 'staff',
    request: { params: idParam, body: contentRevisionCreateSchema },
    responses: {
      201: {
        description: 'Revision',
        body: z.object({ page: contentPageDtoSchema, revision: contentRevisionDtoSchema }),
      },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/content/pages/{id}/actions',
    summary:
      'Workflow action (submit_for_review, approve, publish, schedule, unpublish, archive, rollback)',
    description:
      'Publishing, scheduling and rollback require content.publish and an actor different from the revision author.',
    tags: ['Admin: content'],
    operationId: 'adminContentAction',
    auth: 'staff',
    request: { params: idParam, body: contentPublishActionSchema },
    responses: { 200: { description: 'Updated page', body: contentPageDtoSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/content/preview-render',
    summary: 'Render sanitised HTML from markdown for live preview',
    tags: ['Admin: content'],
    operationId: 'adminContentPreviewRender',
    auth: 'staff',
    request: { body: contentPreviewRenderSchema },
    responses: { 200: { description: 'Sanitised HTML', body: z.object({ html: z.string() }) } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/content/media',
    summary: 'Content media: approved assets and pending uploads',
    description:
      'Approved assets carry their public URLs (/media/{id}). Pending rows are content_media uploads awaiting scanning, derivatives or approval by a content editor other than the uploader (POST /api/v1/files/{id}/public-approval). Private purposes are never listed.',
    tags: ['Admin: content'],
    operationId: 'adminListApprovedMedia',
    auth: 'staff',
    responses: { 200: { description: 'Media', body: contentMediaListResponseSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/redirects',
    summary: 'List redirects',
    tags: ['Admin: content'],
    operationId: 'adminListRedirects',
    auth: 'staff',
    responses: {
      200: { description: 'Redirects', body: z.object({ items: z.array(redirectDtoSchema) }) },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/redirects',
    summary: 'Create a redirect',
    tags: ['Admin: content'],
    operationId: 'adminCreateRedirect',
    auth: 'staff',
    request: { body: redirectUpsertSchema },
    responses: { 201: { description: 'Redirect', body: redirectDtoSchema } },
  }),
  registerRoute({
    method: 'patch',
    path: '/api/v1/admin/redirects/{id}',
    summary: 'Toggle or edit a redirect',
    tags: ['Admin: content'],
    operationId: 'adminPatchRedirect',
    auth: 'staff',
    request: { params: idParam, body: redirectPatchSchema },
    responses: { 200: { description: 'Redirect', body: redirectDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/leads',
    summary: 'List leads (cursor pagination, filters)',
    tags: ['Admin: CRM'],
    operationId: 'adminListLeads',
    auth: 'staff',
    request: { query: leadListQuerySchema },
    responses: { 200: { description: 'Page of leads', body: pageOf(leadDtoSchema) } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/leads/assignees',
    summary: 'Staff users available for assignment',
    tags: ['Admin: CRM'],
    operationId: 'adminListLeadAssignees',
    auth: 'staff',
    responses: {
      200: { description: 'Assignees', body: z.object({ items: z.array(staffAssigneeDtoSchema) }) },
    },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/admin/leads/{id}',
    summary: 'Lead detail with context and internal notes',
    tags: ['Admin: CRM'],
    operationId: 'adminGetLead',
    auth: 'staff',
    request: { params: idParam },
    responses: { 200: { description: 'Lead', body: leadDetailDtoSchema } },
  }),
  registerRoute({
    method: 'patch',
    path: '/api/v1/admin/leads/{id}',
    summary: 'Change status and/or assignment',
    tags: ['Admin: CRM'],
    operationId: 'adminUpdateLead',
    auth: 'staff',
    request: { params: idParam, body: leadUpdateSchema },
    responses: { 200: { description: 'Lead', body: leadDtoSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/leads/{id}/notes',
    summary: 'Add an internal note',
    tags: ['Admin: CRM'],
    operationId: 'adminAddLeadNote',
    auth: 'staff',
    request: { params: idParam, body: leadNoteCreateSchema },
    responses: { 201: { description: 'Note', body: noteDtoSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/admin/leads/{id}/convert',
    summary: 'Convert a lead into a service request or queue an invitation',
    tags: ['Admin: CRM'],
    operationId: 'adminConvertLead',
    auth: 'staff',
    request: { params: idParam, body: leadConvertSchema },
    responses: { 200: { description: 'Result', body: leadConvertResultSchema } },
  }),
];
