import { z } from 'zod';
import {
  allocationsExportQuerySchema,
  assignRequestSchema,
  bankTransferConfirmSchema,
  bankTransferReceiptCreateSchema,
  bankTransferReceiptDtoSchema,
  bankTransferRejectSchema,
  creditNoteCreateSchema,
  creditNoteDtoSchema,
  engagementTransitionResultSchema,
  invoiceCreateSchema,
  invoiceDtoSchema,
  invoiceIssueSchema,
  invoiceListQuerySchema,
  invoiceVoidSchema,
  listRoutes,
  pageOf,
  paymentAttemptCreateSchema,
  paymentAttemptDtoSchema,
  paymentVerifyResultSchema,
  quoteAcceptSchema,
  quoteCreateSchema,
  quoteDtoSchema,
  quoteIssueSchema,
  quoteRejectSchema,
  quoteVersionCreateSchema,
  receiptDtoSchema,
  reconciliationAttemptsQuerySchema,
  reconciliationExceptionDtoSchema,
  refundDecisionSchema,
  refundDtoSchema,
  refundRequestSchema,
  registerRoute,
  staffTransitionSchema,
  triageRequestSchema,
  uuidSchema,
  webhookAckSchema,
  type RouteSpec,
} from '@simplexd/contracts';

/**
 * OpenAPI registration for engagement, invoicing and payment endpoints.
 * Registration is idempotent (hot reloads, test re-imports).
 */
function ensure(spec: RouteSpec): RouteSpec {
  const existing = listRoutes().find((r) => r.operationId === spec.operationId);
  return existing ?? registerRoute(spec);
}

const idParams = z.object({ id: uuidSchema });
const items = <T extends z.ZodTypeAny>(item: T) => z.object({ items: z.array(item) });
const acceptanceResultSchema = z.object({
  quote: quoteDtoSchema,
  invoiceId: uuidSchema.nullable(),
  engagementStatus: z.enum(['awaiting_payment', 'in_progress']),
});
const bankConfirmResultSchema = z.object({
  receipt: bankTransferReceiptDtoSchema,
  receiptNumber: z.string().nullable(),
  invoiceStatus: z.string(),
});

export const financeRoutes: RouteSpec[] = [
  ensure({
    method: 'post',
    path: '/api/v1/service-requests/{id}/triage',
    summary: 'Triage a service request',
    description:
      'Staff `service_requests.triage`: inquiry → triage with project manager, priority and SLA due time from the SLA policies.',
    tags: ['engagements'],
    operationId: 'engagements.triage',
    auth: 'staff',
    request: { params: idParams, body: triageRequestSchema },
    responses: {
      200: { description: 'Triaged', body: engagementTransitionResultSchema },
      409: { description: 'Invalid transition or version conflict' },
    },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/service-requests/{id}/assign',
    summary: 'Assign the project manager',
    tags: ['engagements'],
    operationId: 'engagements.assign',
    auth: 'staff',
    request: { params: idParams, body: assignRequestSchema },
    responses: { 200: { description: 'Assigned', body: engagementTransitionResultSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/service-requests/{id}/transitions/staff',
    summary: 'Staff engagement transition',
    description:
      'Reject, pause, resume, cancel (with billing consequence), override to in_progress, review, deliver, complete.',
    tags: ['engagements'],
    operationId: 'engagements.staffTransition',
    auth: 'staff',
    request: { params: idParams, body: staffTransitionSchema },
    responses: {
      200: { description: 'Transitioned', body: engagementTransitionResultSchema },
      409: { description: 'Invalid transition' },
    },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/service-requests/{id}/quotes',
    summary: 'List quotes for a request',
    tags: ['quotes'],
    operationId: 'quotes.listForRequest',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Quotes', body: items(quoteDtoSchema) } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/service-requests/{id}/quotes',
    summary: 'Draft a quote',
    description:
      'Staff `quotes.issue`: from a template or explicit lines; the server recomputes amounts, tax and totals (integer kobo).',
    tags: ['quotes'],
    operationId: 'quotes.create',
    auth: 'staff',
    request: { params: idParams, body: quoteCreateSchema },
    responses: { 201: { description: 'Draft quote', body: quoteDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/quotes/{id}',
    summary: 'Get a quote',
    tags: ['quotes'],
    operationId: 'quotes.get',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Quote', body: quoteDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/quotes/{id}/versions',
    summary: 'Add a quote version',
    description:
      'Staff `quotes.issue`: the new version supersedes the current one; the quote returns to draft until issued.',
    tags: ['quotes'],
    operationId: 'quotes.addVersion',
    auth: 'staff',
    request: { params: idParams, body: quoteVersionCreateSchema },
    responses: { 201: { description: 'Quote with the new version', body: quoteDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/quotes/{id}/issue',
    summary: 'Issue a quote',
    tags: ['quotes'],
    operationId: 'quotes.issue',
    auth: 'staff',
    request: { params: idParams, body: quoteIssueSchema },
    responses: { 200: { description: 'Issued', body: quoteDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/quotes/{id}/accept',
    summary: 'Accept a quote',
    description:
      'Customer `org.quotes.accept`. Idempotency-Key required. Records signature name, terms version, IP hash and user agent; issues the deposit/service invoice when payment is required.',
    tags: ['quotes'],
    operationId: 'quotes.accept',
    auth: 'session',
    idempotent: true,
    request: { params: idParams, body: quoteAcceptSchema },
    responses: {
      200: { description: 'Accepted', body: acceptanceResultSchema },
      409: { description: 'Newer version issued or already accepted' },
    },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/quotes/{id}/reject',
    summary: 'Reject a quote',
    tags: ['quotes'],
    operationId: 'quotes.reject',
    auth: 'session',
    request: { params: idParams, body: quoteRejectSchema },
    responses: { 200: { description: 'Rejected', body: quoteDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/invoices',
    summary: 'List invoices',
    tags: ['invoices'],
    operationId: 'invoices.list',
    auth: 'session',
    request: { query: invoiceListQuerySchema },
    responses: { 200: { description: 'Invoices', body: pageOf(invoiceDtoSchema) } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices',
    summary: 'Create an invoice (finance)',
    description: 'Staff `finance.invoices.manage` (step-up authentication).',
    tags: ['invoices'],
    operationId: 'invoices.create',
    auth: 'staff',
    request: { body: invoiceCreateSchema },
    responses: { 201: { description: 'Invoice', body: invoiceDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/invoices/{id}',
    summary: 'Get an invoice',
    tags: ['invoices'],
    operationId: 'invoices.get',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Invoice', body: invoiceDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices/{id}/issue',
    summary: 'Issue an invoice',
    tags: ['invoices'],
    operationId: 'invoices.issue',
    auth: 'staff',
    request: { params: idParams, body: invoiceIssueSchema },
    responses: { 200: { description: 'Issued', body: invoiceDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices/{id}/void',
    summary: 'Void an invoice',
    tags: ['invoices'],
    operationId: 'invoices.void',
    auth: 'staff',
    request: { params: idParams, body: invoiceVoidSchema },
    responses: { 200: { description: 'Voided', body: invoiceDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices/{id}/payment-attempts',
    summary: 'Start a payment',
    description:
      'Customer `org.invoices.pay`. Idempotency-Key required. Server-created attempt with immutable reference, amount and currency; hosted checkout URL returned; no secrets.',
    tags: ['payments'],
    operationId: 'payments.createAttempt',
    auth: 'session',
    idempotent: true,
    request: { params: idParams, body: paymentAttemptCreateSchema },
    responses: {
      201: { description: 'Payment attempt', body: paymentAttemptDtoSchema },
      503: { description: 'Provider not configured' },
    },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices/{id}/bank-transfer-receipts',
    summary: 'Declare a bank transfer',
    tags: ['payments'],
    operationId: 'payments.declareBankTransfer',
    auth: 'session',
    request: { params: idParams, body: bankTransferReceiptCreateSchema },
    responses: {
      201: { description: 'Declared (not cleared money)', body: bankTransferReceiptDtoSchema },
    },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/invoices/{id}/credit-notes',
    summary: 'Issue a credit note',
    tags: ['invoices'],
    operationId: 'invoices.creditNote',
    auth: 'staff',
    request: { params: idParams, body: creditNoteCreateSchema },
    responses: { 201: { description: 'Credit note', body: creditNoteDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/invoices/{id}/receipts',
    summary: 'Receipts for an invoice',
    tags: ['invoices'],
    operationId: 'invoices.receipts',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Receipts', body: items(receiptDtoSchema) } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/payment-attempts/{id}',
    summary: 'Get a payment attempt',
    tags: ['payments'],
    operationId: 'payments.getAttempt',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Attempt', body: paymentAttemptDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/payment-attempts/{id}/verify',
    summary: 'Verify a payment with the provider',
    description:
      'Settles only when provider status, reference, amount and currency match; mismatches become uncertain with a reconciliation exception.',
    tags: ['payments'],
    operationId: 'payments.verify',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Verification outcome', body: paymentVerifyResultSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/payment-attempts/callback',
    summary: 'Hosted checkout callback',
    description:
      'Verifies on the server then redirects to the invoice. A redirect is never settlement.',
    tags: ['payments'],
    operationId: 'payments.callback',
    auth: 'session',
    request: { query: z.object({ reference: z.string() }) },
    responses: { 303: { description: 'Redirect to the invoice' } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/refunds',
    summary: 'Request a refund',
    tags: ['refunds'],
    operationId: 'refunds.request',
    auth: 'session',
    idempotent: true,
    request: { body: refundRequestSchema },
    responses: { 201: { description: 'Refund requested', body: refundDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/refunds/{id}',
    summary: 'Get a refund',
    tags: ['refunds'],
    operationId: 'refunds.get',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Refund', body: refundDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/refunds/{id}/approve',
    summary: 'Approve a refund',
    description:
      'Staff `finance.refunds.approve`, step-up authentication, approver must differ from the requester.',
    tags: ['refunds'],
    operationId: 'refunds.approve',
    auth: 'staff',
    request: { params: idParams, body: refundDecisionSchema },
    responses: { 200: { description: 'Approved', body: refundDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/refunds/{id}/reject',
    summary: 'Reject a refund',
    tags: ['refunds'],
    operationId: 'refunds.reject',
    auth: 'staff',
    request: { params: idParams, body: refundDecisionSchema },
    responses: { 200: { description: 'Rejected', body: refundDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/bank-transfer-receipts/{id}',
    summary: 'Get a declared bank transfer',
    tags: ['payments'],
    operationId: 'payments.getBankTransfer',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Receipt', body: bankTransferReceiptDtoSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/bank-transfer-receipts/{id}/confirm',
    summary: 'Confirm a bank transfer (finance)',
    description:
      'Staff `finance.allocations.manage`, step-up authentication. Allocation, journal and receipt are posted once.',
    tags: ['payments'],
    operationId: 'payments.confirmBankTransfer',
    auth: 'staff',
    request: { params: idParams, body: bankTransferConfirmSchema },
    responses: { 200: { description: 'Confirmed', body: bankConfirmResultSchema } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/bank-transfer-receipts/{id}/reject',
    summary: 'Reject a bank transfer declaration',
    tags: ['payments'],
    operationId: 'payments.rejectBankTransfer',
    auth: 'staff',
    request: { params: idParams, body: bankTransferRejectSchema },
    responses: { 200: { description: 'Rejected', body: bankTransferReceiptDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/credit-notes/{id}',
    summary: 'Get a credit note',
    tags: ['invoices'],
    operationId: 'invoices.getCreditNote',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Credit note', body: creditNoteDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/receipts/{id}',
    summary: 'Get a receipt',
    tags: ['invoices'],
    operationId: 'invoices.getReceipt',
    auth: 'session',
    request: { params: idParams },
    responses: { 200: { description: 'Receipt', body: receiptDtoSchema } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/finance/reconciliation/attempts',
    summary: 'Attempts awaiting reconciliation',
    tags: ['finance'],
    operationId: 'finance.reconciliationAttempts',
    auth: 'staff',
    request: { query: reconciliationAttemptsQuerySchema },
    responses: { 200: { description: 'Attempts', body: items(paymentAttemptDtoSchema) } },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/finance/reconciliation/exceptions',
    summary: 'Reconciliation exceptions',
    tags: ['finance'],
    operationId: 'finance.reconciliationExceptions',
    auth: 'staff',
    responses: {
      200: { description: 'Exceptions', body: items(reconciliationExceptionDtoSchema) },
    },
  }),
  ensure({
    method: 'get',
    path: '/api/v1/finance/exports/allocations.csv',
    summary: 'Export allocations (CSV)',
    description:
      'Staff `finance.export`: one row per allocation with receipt number and journal debit/credit totals.',
    tags: ['finance'],
    operationId: 'finance.exportAllocations',
    auth: 'staff',
    request: { query: allocationsExportQuerySchema },
    responses: { 200: { description: 'CSV' } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/webhooks/paystack',
    summary: 'Paystack webhook',
    description:
      'HMAC-SHA512 over the exact raw body. Authentic events are persisted and deduplicated before the 200; invalid signatures get 401.',
    tags: ['payments', 'webhooks'],
    operationId: 'payments.paystackWebhook',
    auth: 'webhook',
    responses: {
      200: { description: 'Acknowledged', body: webhookAckSchema },
      401: { description: 'Invalid signature' },
    },
  }),
];
