import { z } from 'zod';
import {
  accountDeletionRequestSchema,
  consentDtoSchema,
  notificationPreferencesDtoSchema,
  notificationPreferencesUpdateSchema,
  onboardingCompleteSchema,
  organizationInvitationDtoSchema,
  organizationInviteSchema,
  organizationMemberDtoSchema,
  organizationMembershipDtoSchema,
  organizationUpdateSchema,
  pageOf,
  phoneUpdateSchema,
  registerRoute,
  serviceRequestCreateSchema,
  serviceRequestDetailSchema,
  serviceRequestDtoSchema,
  serviceRequestListQuerySchema,
  serviceRequestNoteCreateSchema,
  serviceRequestTransitionSchema,
  noteDtoSchema,
  slugSchema,
  uuidSchema,
} from '@simplexd/contracts';

/** OpenAPI registrations for the customer portal endpoints. */

const idParam = z.object({ id: uuidSchema });

export const portalRoutes = [
  registerRoute({
    method: 'get',
    path: '/api/v1/service-requests',
    summary: 'List the active organisation’s service requests',
    tags: ['Service requests'],
    operationId: 'listServiceRequests',
    auth: 'session',
    request: { query: serviceRequestListQuerySchema },
    responses: { 200: { description: 'Page of requests', body: pageOf(serviceRequestDtoSchema) } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/service-requests',
    summary: 'Create a service request (customer intake)',
    description:
      'Creates the request in `inquiry` with reference SR-<year>-<sequence>, the first engagement transition, an outbox event and an audit entry.',
    tags: ['Service requests'],
    operationId: 'createServiceRequest',
    auth: 'session',
    request: { body: serviceRequestCreateSchema },
    responses: { 201: { description: 'Created request', body: serviceRequestDtoSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/service-requests/interest',
    summary: 'Register interest in a service that is not bookable yet',
    description: 'Creates a lead with source quote_request instead of a service request.',
    tags: ['Service requests'],
    operationId: 'registerServiceInterest',
    auth: 'session',
    request: {
      body: z.object({
        serviceSlug: slugSchema,
        message: z.string().max(4000).optional(),
        marketId: uuidSchema.nullable().optional(),
        scenarioId: uuidSchema.nullable().optional(),
        budgetNaira: z.number().positive().nullable().optional(),
      }),
    },
    responses: {
      201: {
        description: 'Lead recorded',
        body: z.object({ leadId: uuidSchema, status: z.string() }),
      },
    },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/service-requests/{id}',
    summary: 'Service request detail with timeline and notes',
    tags: ['Service requests'],
    operationId: 'getServiceRequest',
    auth: 'session',
    request: { params: idParam },
    responses: { 200: { description: 'Detail', body: serviceRequestDetailSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/service-requests/{id}/transitions',
    summary: 'Customer transition (cancel, pause, resume)',
    description:
      'Validated by the engagement state machine; cancel and pause require a reason; optimistic concurrency via expectedVersion.',
    tags: ['Service requests'],
    operationId: 'transitionServiceRequest',
    auth: 'session',
    request: { params: idParam, body: serviceRequestTransitionSchema },
    responses: { 200: { description: 'Updated request', body: serviceRequestDtoSchema } },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/service-requests/{id}/notes',
    summary: 'Add a customer-visible note to a request',
    tags: ['Service requests'],
    operationId: 'addServiceRequestNote',
    auth: 'session',
    request: { params: idParam, body: serviceRequestNoteCreateSchema },
    responses: { 201: { description: 'Note', body: noteDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/me/notification-preferences',
    summary: 'Notification preferences matrix',
    tags: ['Me'],
    operationId: 'getNotificationPreferences',
    auth: 'session',
    responses: { 200: { description: 'Preferences', body: notificationPreferencesDtoSchema } },
  }),
  registerRoute({
    method: 'put',
    path: '/api/v1/me/notification-preferences',
    summary: 'Replace notification preferences',
    tags: ['Me'],
    operationId: 'updateNotificationPreferences',
    auth: 'session',
    request: { body: notificationPreferencesUpdateSchema },
    responses: { 200: { description: 'Preferences', body: notificationPreferencesDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/me/organizations',
    summary: 'Memberships with organisation names',
    tags: ['Me'],
    operationId: 'listMyOrganizations',
    auth: 'session',
    responses: {
      200: {
        description: 'Memberships',
        body: z.object({ items: z.array(organizationMembershipDtoSchema) }),
      },
    },
  }),
  registerRoute({
    method: 'patch',
    path: '/api/v1/me/organizations',
    summary: 'Update the active organisation (name, ownership type)',
    tags: ['Me'],
    operationId: 'updateActiveOrganization',
    auth: 'session',
    request: { body: organizationUpdateSchema },
    responses: { 200: { description: 'Membership', body: organizationMembershipDtoSchema } },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/me/organizations/members',
    summary: 'Members of the active organisation',
    tags: ['Me'],
    operationId: 'listOrganizationMembers',
    auth: 'session',
    responses: {
      200: {
        description: 'Members',
        body: z.object({ items: z.array(organizationMemberDtoSchema) }),
      },
    },
  }),
  registerRoute({
    method: 'get',
    path: '/api/v1/me/organizations/invitations',
    summary: 'Pending invitations of the active organisation',
    tags: ['Me'],
    operationId: 'listOrganizationInvitations',
    auth: 'session',
    responses: {
      200: {
        description: 'Invitations',
        body: z.object({ items: z.array(organizationInvitationDtoSchema) }),
      },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/me/organizations/invitations',
    summary: 'Invite a member (owner, member, adviser, approver)',
    tags: ['Me'],
    operationId: 'inviteOrganizationMember',
    auth: 'session',
    request: { body: organizationInviteSchema },
    responses: { 201: { description: 'Invitation', body: organizationInvitationDtoSchema } },
  }),
  registerRoute({
    method: 'delete',
    path: '/api/v1/me/organizations/invitations/{id}',
    summary: 'Revoke a pending invitation',
    tags: ['Me'],
    operationId: 'revokeOrganizationInvitation',
    auth: 'session',
    request: { params: z.object({ id: z.string() }) },
    responses: {
      200: {
        description: 'Revoked',
        body: z.object({ id: z.string(), status: z.literal('canceled') }),
      },
    },
  }),
  registerRoute({
    method: 'patch',
    path: '/api/v1/me/phone',
    summary: 'Set or clear the phone number (validated, stored as E.164)',
    tags: ['Me'],
    operationId: 'updatePhone',
    auth: 'session',
    request: { body: phoneUpdateSchema },
    responses: {
      200: { description: 'Phone', body: z.object({ phoneE164: z.string().nullable() }) },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/me/onboarding',
    summary: 'Mark onboarding complete',
    tags: ['Me'],
    operationId: 'completeOnboarding',
    auth: 'session',
    request: { body: onboardingCompleteSchema },
    responses: {
      200: { description: 'Completed', body: z.object({ onboardingCompletedAt: z.string() }) },
    },
  }),
  registerRoute({
    method: 'post',
    path: '/api/v1/me/account-deletion',
    summary: 'Request account deletion (creates a support lead and audit entry)',
    tags: ['Me'],
    operationId: 'requestAccountDeletion',
    auth: 'session',
    request: { body: accountDeletionRequestSchema },
    responses: {
      201: {
        description: 'Recorded',
        body: z.object({
          leadId: uuidSchema,
          alreadyRequested: z.boolean(),
          retentionPolicy: z.string(),
        }),
      },
    },
  }),
];

export { consentDtoSchema as portalConsentDtoSchema };
