import { z } from 'zod';
import {
  arrearsDtoSchema,
  assetCreateSchema,
  assetDtoSchema,
  assetListQuerySchema,
  assetUpdateSchema,
  cursorPaginationQuerySchema,
  dateOnlySchema,
  estateCreateSchema,
  estateDtoSchema,
  estateServiceChargeResultSchema,
  estateServiceChargeRunSchema,
  leaseBalanceDtoSchema,
  leaseCreateSchema,
  leaseDtoSchema,
  leaseListQuerySchema,
  leaseNoticeSchema,
  leasePartyDtoSchema,
  leasePartyInviteSchema,
  leasePartyRevokeSchema,
  leaseRenewSchema,
  leaseTerminateSchema,
  leaseTransitionSchema,
  leaseUpdateSchema,
  listRoutes,
  ownerStatementDtoSchema,
  ownerStatementGenerateSchema,
  ownerStatementListQuerySchema,
  pageOf,
  payoutDecisionSchema,
  payoutDtoSchema,
  payoutProposeSchema,
  payoutSettleSchema,
  payoutStatusSchema,
  registerRoute,
  rentChargeCreateSchema,
  rentChargeDtoSchema,
  rentInvoicingRunDtoSchema,
  rentScheduleDtoSchema,
  stayBookingCreateSchema,
  stayBookingDtoSchema,
  stayBookingTransitionSchema,
  stayCalendarQuerySchema,
  tenantAppointmentDtoSchema,
  tenantInvitationAcceptSchema,
  tenantLeaseSummarySchema,
  tenantNoticeDtoSchema,
  tenantReceiptDtoSchema,
  uuidSchema,
  warrantyCreateSchema,
  workOrderApproveSchema,
  workOrderAssignSchema,
  workOrderCompleteSchema,
  workOrderCreateSchema,
  workOrderDtoSchema,
  workOrderEstimateSchema,
  workOrderEvidenceSchema,
  workOrderListQuerySchema,
  workOrderRejectSchema,
  workOrderSimpleTransitionSchema,
  workOrderTriageSchema,
  workOrderVerifySchema,
  type RouteSpec,
} from '@simplexd/contracts';

/**
 * OpenAPI registration for property management: leases, rent, the tenant
 * portal, maintenance, assets, owner statements, payouts, estates and short
 * stays. Expansion endpoints answer 404 `feature_disabled` unless the
 * corresponding `expansion.*` flag is on for the caller. Registration is
 * idempotent (hot reloads, test re-imports).
 */
function ensure(spec: RouteSpec): RouteSpec {
  const existing = listRoutes().find((r) => r.operationId === spec.operationId);
  return existing ?? registerRoute(spec);
}

const idParams = z.object({ id: uuidSchema });
const items = <T extends z.ZodTypeAny>(item: T) => z.object({ items: z.array(item) });
const post = (
  path: string,
  operationId: string,
  summary: string,
  body: z.ZodTypeAny | undefined,
  response: z.ZodTypeAny,
  extra: Partial<RouteSpec> = {},
): RouteSpec =>
  ensure({
    method: 'post',
    path,
    summary,
    tags: extra.tags ?? ['rentals'],
    operationId,
    auth: extra.auth ?? 'session',
    request: { params: idParams, ...(body ? { body } : {}) },
    responses: { 200: { description: 'OK', body: response }, 409: { description: 'Invalid transition or version conflict' } },
    ...extra,
  });

export const rentalRoutes: RouteSpec[] = [
  // Leases
  ensure({
    method: 'get',
    path: '/api/v1/leases',
    summary: 'List leases',
    description: 'Owner organisation members (`org.read`) see their own leases; staff (`rentals.manage`, `customers.read`, `finance.read`) may scope by organizationId.',
    tags: ['rentals'],
    operationId: 'leases.list',
    auth: 'session',
    request: { query: leaseListQuerySchema },
    responses: { 200: { description: 'Leases', body: pageOf(leaseDtoSchema) } },
  }),
  ensure({
    method: 'post',
    path: '/api/v1/leases',
    summary: 'Create a lease',
    description:
      '`org.leases.manage` or staff `rentals.manage`. Student leases (`student_academic`, guarantor) need `expansion.student_housing`; move-in inventories need `expansion.rental_placement`.',
    tags: ['rentals'],
    operationId: 'leases.create',
    auth: 'session',
    request: { body: leaseCreateSchema },
    responses: { 201: { description: 'Draft lease', body: leaseDtoSchema } },
  }),
  ensure({ method: 'get', path: '/api/v1/leases/{id}', summary: 'Get a lease', tags: ['rentals'], operationId: 'leases.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Lease', body: leaseDtoSchema } } }),
  ensure({ method: 'patch', path: '/api/v1/leases/{id}', summary: 'Update lease terms', description: 'Dates, rent and period are frozen once the lease is active.', tags: ['rentals'], operationId: 'leases.update', auth: 'session', request: { params: idParams, body: leaseUpdateSchema }, responses: { 200: { description: 'Lease', body: leaseDtoSchema }, 409: { description: 'Version conflict' } } }),
  post('/api/v1/leases/{id}/transition', 'leases.transition', 'Lease transition', leaseTransitionSchema, leaseDtoSchema, { description: 'draft → pending_signature | active (schedule generated), active → ended (staff). `leaseMachine`.' }),
  post('/api/v1/leases/{id}/terminate', 'leases.terminate', 'Terminate a lease with a reason', leaseTerminateSchema, leaseDtoSchema),
  post('/api/v1/leases/{id}/renew', 'leases.renew', 'Renew a lease', leaseRenewSchema, z.object({ previous: leaseDtoSchema, renewal: leaseDtoSchema })),
  ensure({ method: 'get', path: '/api/v1/leases/{id}/parties', summary: 'Lease parties', description: 'Tenants see only their own party record.', tags: ['rentals'], operationId: 'leases.parties', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Parties', body: items(leasePartyDtoSchema) } } }),
  post('/api/v1/leases/{id}/parties', 'leases.invite', 'Invite a tenant or occupant', leasePartyInviteSchema, leasePartyDtoSchema, { description: 'Single-use token with expiry, e-mailed through the `tenant.invited` outbox event.' }),
  ensure({ method: 'post', path: '/api/v1/leases/{id}/parties/{partyId}/revoke', summary: 'Revoke a party\'s access', tags: ['rentals'], operationId: 'leases.revokeParty', auth: 'session', request: { params: z.object({ id: uuidSchema, partyId: uuidSchema }), body: leasePartyRevokeSchema }, responses: { 200: { description: 'Party', body: leasePartyDtoSchema } } }),
  post('/api/v1/leases/{id}/notices', 'leases.notice', 'Post a notice to the lease\'s tenants', leaseNoticeSchema, z.object({ recipients: z.number().int() })),
  ensure({ method: 'get', path: '/api/v1/leases/{id}/schedule', summary: 'Rent schedule', tags: ['rentals'], operationId: 'leases.schedule', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Periods', body: items(rentScheduleDtoSchema) } } }),
  ensure({ method: 'get', path: '/api/v1/leases/{id}/charges', summary: 'Charges with balances', tags: ['rentals'], operationId: 'leases.charges', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Charges', body: items(rentChargeDtoSchema) } } }),
  post('/api/v1/leases/{id}/charges', 'leases.addCharge', 'Raise an ad-hoc charge (late fee, utility, other)', rentChargeCreateSchema, rentChargeDtoSchema),
  ensure({ method: 'get', path: '/api/v1/leases/{id}/balance', summary: 'Lease balance and arrears ageing', tags: ['rentals'], operationId: 'leases.balance', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Balance', body: leaseBalanceDtoSchema.extend({ arrears: arrearsDtoSchema }) } } }),
  ensure({
    method: 'post',
    path: '/api/v1/rent/invoicing-runs',
    summary: 'Run rent invoicing now',
    description: 'Staff `rentals.manage`: issues rent invoices for periods due within the lead window (the hourly job does the same).',
    tags: ['rentals'],
    operationId: 'rent.invoicingRun',
    auth: 'staff',
    request: { body: z.object({ asOf: dateOnlySchema.optional(), leadDays: z.number().int().optional() }) },
    responses: { 200: { description: 'Run', body: rentInvoicingRunDtoSchema } },
  }),
  // Tenant portal
  ensure({ method: 'get', path: '/api/v1/tenant/leases', summary: 'My leases (tenant)', description: '`tenant.lease.view`: only leases where the caller is an active party.', tags: ['tenant'], operationId: 'tenant.leases', auth: 'session', responses: { 200: { description: 'Leases', body: items(tenantLeaseSummarySchema) } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/leases/{id}', summary: 'My lease (tenant)', tags: ['tenant'], operationId: 'tenant.lease', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Lease', body: tenantLeaseSummarySchema } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/leases/{id}/balance', summary: 'My balance (tenant)', tags: ['tenant'], operationId: 'tenant.balance', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Balance', body: leaseBalanceDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/leases/{id}/charges', summary: 'My charges (tenant)', tags: ['tenant'], operationId: 'tenant.charges', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Charges', body: items(rentChargeDtoSchema) } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/leases/{id}/tickets', summary: 'My tickets on a lease (tenant)', tags: ['tenant'], operationId: 'tenant.leaseTickets', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Tickets', body: items(workOrderDtoSchema) } } }),
  ensure({ method: 'post', path: '/api/v1/tenant/leases/{id}/tickets', summary: 'Raise a maintenance ticket (tenant)', description: '`tenant.maintenance.request` on the caller\'s own lease.', tags: ['tenant'], operationId: 'tenant.createTicket', auth: 'session', request: { params: idParams, body: workOrderCreateSchema.pick({ title: true, description: true, category: true, priority: true }) }, responses: { 201: { description: 'Ticket', body: workOrderDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/receipts', summary: 'My receipts (tenant)', tags: ['tenant'], operationId: 'tenant.receipts', auth: 'session', responses: { 200: { description: 'Receipts', body: items(tenantReceiptDtoSchema) } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/tickets', summary: 'My tickets (tenant)', tags: ['tenant'], operationId: 'tenant.tickets', auth: 'session', responses: { 200: { description: 'Tickets', body: items(workOrderDtoSchema) } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/appointments', summary: 'My appointments (tenant)', tags: ['tenant'], operationId: 'tenant.appointments', auth: 'session', responses: { 200: { description: 'Appointments', body: items(tenantAppointmentDtoSchema) } } }),
  ensure({ method: 'get', path: '/api/v1/tenant/notices', summary: 'Approved notices (tenant)', tags: ['tenant'], operationId: 'tenant.notices', auth: 'session', responses: { 200: { description: 'Notices', body: items(tenantNoticeDtoSchema) } } }),
  ensure({ method: 'post', path: '/api/v1/tenant/invitations/accept', summary: 'Accept a lease invitation', description: 'Signed in with the invited e-mail; the token is single-use and expires.', tags: ['tenant'], operationId: 'tenant.acceptInvitation', auth: 'session', request: { body: tenantInvitationAcceptSchema }, responses: { 200: { description: 'Party', body: leasePartyDtoSchema }, 409: { description: 'Expired' } } }),
  // Maintenance
  ensure({ method: 'get', path: '/api/v1/work-orders', summary: 'List work orders', description: 'Staff by organisation; owners their organisation; tenants and partners only what they reported, are a party of, or are assigned to.', tags: ['maintenance'], operationId: 'workOrders.list', auth: 'session', request: { query: workOrderListQuerySchema }, responses: { 200: { description: 'Work orders', body: pageOf(workOrderDtoSchema) } } }),
  ensure({ method: 'post', path: '/api/v1/work-orders', summary: 'Request maintenance', description: '`org.maintenance.request` (owner), `tenant.maintenance.request` (tenant, with leaseId) or staff `maintenance.manage`. SLA deadline set from the priority.', tags: ['maintenance'], operationId: 'workOrders.create', auth: 'session', request: { body: workOrderCreateSchema }, responses: { 201: { description: 'Work order', body: workOrderDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/work-orders/{id}', summary: 'Get a work order', tags: ['maintenance'], operationId: 'workOrders.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Work order', body: workOrderDtoSchema } } }),
  post('/api/v1/work-orders/{id}/triage', 'workOrders.triage', 'Triage (staff)', workOrderTriageSchema, workOrderDtoSchema, { tags: ['maintenance'], auth: 'staff' }),
  post('/api/v1/work-orders/{id}/assign', 'workOrders.assign', 'Dispatch a contractor (staff)', workOrderAssignSchema, workOrderDtoSchema, { tags: ['maintenance'], auth: 'staff', description: 'Creates an accepted `contractor` assignment for a staff member or registered partner.' }),
  post('/api/v1/work-orders/{id}/start', 'workOrders.start', 'Start work (assignee or staff)', workOrderSimpleTransitionSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/request-approval', 'workOrders.requestApproval', 'Submit an estimate for owner approval', workOrderEstimateSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/approve', 'workOrders.approve', 'Owner approves the cost', workOrderApproveSchema, workOrderDtoSchema, { tags: ['maintenance'], description: '`org.change_orders.approve`.' }),
  post('/api/v1/work-orders/{id}/reject', 'workOrders.reject', 'Reject with a reason', workOrderRejectSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/cancel', 'workOrders.cancel', 'Cancel with a reason', workOrderRejectSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/evidence', 'workOrders.evidence', 'Attach evidence files', workOrderEvidenceSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/complete', 'workOrders.complete', 'Complete (evidence required)', workOrderCompleteSchema, workOrderDtoSchema, { tags: ['maintenance'] }),
  post('/api/v1/work-orders/{id}/verify', 'workOrders.verify', 'Verify and record the recoverable expense', workOrderVerifySchema, workOrderDtoSchema, { tags: ['maintenance'], description: 'Staff or owner. Posts `work_order:<id>:expense` (Dr 5200 / Cr 2400).' }),
  post('/api/v1/work-orders/{id}/close', 'workOrders.close', 'Close (staff)', workOrderSimpleTransitionSchema, workOrderDtoSchema, { tags: ['maintenance'], auth: 'staff' }),
  // Assets
  ensure({ method: 'get', path: '/api/v1/assets', summary: 'Asset register', description: '`expansion.preventive_maintenance`.', tags: ['maintenance'], operationId: 'assets.list', auth: 'session', request: { query: assetListQuerySchema }, responses: { 200: { description: 'Assets', body: pageOf(assetDtoSchema) }, 404: { description: 'feature_disabled' } } }),
  ensure({ method: 'post', path: '/api/v1/assets', summary: 'Register an asset', tags: ['maintenance'], operationId: 'assets.create', auth: 'session', request: { body: assetCreateSchema }, responses: { 201: { description: 'Asset', body: assetDtoSchema }, 404: { description: 'feature_disabled' } } }),
  ensure({ method: 'get', path: '/api/v1/assets/{id}', summary: 'Get an asset', tags: ['maintenance'], operationId: 'assets.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Asset', body: assetDtoSchema } } }),
  ensure({ method: 'patch', path: '/api/v1/assets/{id}', summary: 'Update an asset', tags: ['maintenance'], operationId: 'assets.update', auth: 'session', request: { params: idParams, body: assetUpdateSchema }, responses: { 200: { description: 'Asset', body: assetDtoSchema } } }),
  post('/api/v1/assets/{id}/warranties', 'assets.addWarranty', 'Add a warranty', warrantyCreateSchema, assetDtoSchema, { tags: ['maintenance'] }),
  // Owner statements and payouts
  ensure({ method: 'get', path: '/api/v1/owner-statements', summary: 'List owner statements', description: 'Owners see reconciled and issued statements of their organisation; staff see drafts too.', tags: ['owner-statements'], operationId: 'ownerStatements.list', auth: 'session', request: { query: ownerStatementListQuerySchema }, responses: { 200: { description: 'Statements', body: pageOf(ownerStatementDtoSchema) } } }),
  ensure({ method: 'post', path: '/api/v1/owner-statements', summary: 'Generate a period statement', description: 'Staff `rentals.manage`. Rent and service charges collected (settled allocations), management fee per lease, verified maintenance recoveries, arrears and open obligations.', tags: ['owner-statements'], operationId: 'ownerStatements.generate', auth: 'staff', request: { body: ownerStatementGenerateSchema }, responses: { 201: { description: 'Draft statement', body: ownerStatementDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/owner-statements/{id}', summary: 'Get an owner statement', tags: ['owner-statements'], operationId: 'ownerStatements.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Statement', body: ownerStatementDtoSchema } } }),
  post('/api/v1/owner-statements/{id}/reconcile', 'ownerStatements.reconcile', 'Reconcile to allocations and journals', undefined, ownerStatementDtoSchema, { tags: ['owner-statements'], auth: 'staff', description: 'Posts the fee and recovery journals, recomputes totals from finance truth; reconciled only when every figure matches.' }),
  post('/api/v1/owner-statements/{id}/issue', 'ownerStatements.issue', 'Issue to the owner', undefined, ownerStatementDtoSchema, { tags: ['owner-statements'], auth: 'staff' }),
  ensure({ method: 'get', path: '/api/v1/payouts', summary: 'List payouts', tags: ['payouts'], operationId: 'payouts.list', auth: 'session', request: { query: cursorPaginationQuerySchema.extend({ organizationId: z.string().optional(), status: payoutStatusSchema.optional() }) }, responses: { 200: { description: 'Payouts', body: pageOf(payoutDtoSchema) } } }),
  ensure({ method: 'post', path: '/api/v1/payouts', summary: 'Propose an owner distribution', description: 'From a reconciled statement; never above the net payable.', tags: ['payouts'], operationId: 'payouts.propose', auth: 'staff', request: { body: payoutProposeSchema }, responses: { 201: { description: 'Payout', body: payoutDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/payouts/{id}', summary: 'Get a payout', tags: ['payouts'], operationId: 'payouts.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Payout', body: payoutDtoSchema } } }),
  post('/api/v1/payouts/{id}/first-approve', 'payouts.firstApprove', 'First approval', undefined, payoutDtoSchema, { tags: ['payouts'], auth: 'staff', description: '`finance.payouts.first_approve` (step-up); not the proposer; reconciliation must be balanced.' }),
  post('/api/v1/payouts/{id}/second-approve', 'payouts.secondApprove', 'Second approval (different approver)', undefined, payoutDtoSchema, { tags: ['payouts'], auth: 'staff', description: '`finance.payouts.second_approve` by someone other than the first approver. Posts `payout:<id>:approved` (Dr 2100 / Cr 2400).' }),
  post('/api/v1/payouts/{id}/reject', 'payouts.reject', 'Reject a payout', payoutDecisionSchema, payoutDtoSchema, { tags: ['payouts'], auth: 'staff' }),
  post('/api/v1/payouts/{id}/submit', 'payouts.submit', 'Mark as sent to the bank', undefined, payoutDtoSchema, { tags: ['payouts'], auth: 'staff', description: '`finance.reconcile`.' }),
  post('/api/v1/payouts/{id}/settle', 'payouts.settle', 'Settle against the bank statement', payoutSettleSchema, payoutDtoSchema, { tags: ['payouts'], auth: 'staff', description: '`finance.reconcile`. Posts `payout:<id>:settled` (Dr 2400 / Cr 1000).' }),
  post('/api/v1/payouts/{id}/fail', 'payouts.fail', 'Record a failed transfer', payoutDecisionSchema, payoutDtoSchema, { tags: ['payouts'], auth: 'staff' }),
  // Estates
  ensure({ method: 'get', path: '/api/v1/estates', summary: 'List estates', description: '`expansion.estate_management`.', tags: ['estates'], operationId: 'estates.list', auth: 'session', request: { query: z.object({ organizationId: z.string().optional() }) }, responses: { 200: { description: 'Estates', body: items(estateDtoSchema) }, 404: { description: 'feature_disabled' } } }),
  ensure({ method: 'post', path: '/api/v1/estates', summary: 'Create an estate', description: 'Staff `estates.manage` or `org.properties.manage`; separate ledger segment.', tags: ['estates'], operationId: 'estates.create', auth: 'session', request: { body: estateCreateSchema }, responses: { 201: { description: 'Estate', body: estateDtoSchema } } }),
  ensure({ method: 'get', path: '/api/v1/estates/{id}', summary: 'Get an estate', tags: ['estates'], operationId: 'estates.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Estate', body: estateDtoSchema } } }),
  post('/api/v1/estates/{id}/properties', 'estates.attachProperty', 'Attach a property', z.object({ propertyId: uuidSchema }), estateDtoSchema, { tags: ['estates'] }),
  post('/api/v1/estates/{id}/service-charges', 'estates.serviceCharges', 'Invoice the service charge to every active lease', estateServiceChargeRunSchema, estateServiceChargeResultSchema, { tags: ['estates'], auth: 'staff', description: 'Staff `estates.manage`; `service_charge` invoices on the estate ledger segment.' }),
  ensure({ method: 'get', path: '/api/v1/estates/{id}/issues', summary: 'Resident issues (work orders in the estate)', tags: ['estates'], operationId: 'estates.issues', auth: 'session', request: { params: idParams, query: workOrderListQuerySchema.omit({ estateId: true }) }, responses: { 200: { description: 'Work orders', body: pageOf(workOrderDtoSchema) } } }),
  // Short stay
  ensure({ method: 'get', path: '/api/v1/rent/stays', summary: 'Short-stay calendar', description: '`expansion.short_stay`.', tags: ['short-stay'], operationId: 'stays.calendar', auth: 'session', request: { query: stayCalendarQuerySchema }, responses: { 200: { description: 'Bookings', body: items(stayBookingDtoSchema) }, 404: { description: 'feature_disabled' } } }),
  ensure({ method: 'post', path: '/api/v1/rent/stays', summary: 'Book a stay', description: 'Atomic no-overlap check per unit; same-day turnover allowed.', tags: ['short-stay'], operationId: 'stays.create', auth: 'session', request: { body: stayBookingCreateSchema }, responses: { 201: { description: 'Booking', body: stayBookingDtoSchema }, 409: { description: 'slot_unavailable' } } }),
  ensure({ method: 'get', path: '/api/v1/rent/stays/{id}', summary: 'Get a booking', tags: ['short-stay'], operationId: 'stays.get', auth: 'session', request: { params: idParams }, responses: { 200: { description: 'Booking', body: stayBookingDtoSchema } } }),
  post('/api/v1/rent/stays/{id}/transition', 'stays.transition', 'Confirm, check in, check out (turnover work order) or cancel', stayBookingTransitionSchema, stayBookingDtoSchema, { tags: ['short-stay'] }),
];
