import { BLOCKED_EXTENSIONS } from '@simplexd/domain/evidence';
import { StorageError } from './types';

/**
 * Storage keys are generated by the server, never taken from clients. The
 * character set is deliberately narrow so keys are safe in URLs, file paths
 * and copy-source headers on every S3-compatible store.
 */

export const STORAGE_KEY_PATTERN = /^[a-z0-9/_.-]+$/;
export const STORAGE_KEY_MAX_LENGTH = 900;

export function isValidStorageKey(key: string): boolean {
  if (typeof key !== 'string' || key.length === 0 || key.length > STORAGE_KEY_MAX_LENGTH)
    return false;
  if (!STORAGE_KEY_PATTERN.test(key)) return false;
  if (key.startsWith('/') || key.endsWith('/') || key.includes('//')) return false;
  const segments = key.split('/');
  return segments.every(
    (segment) => segment !== '.' && segment !== '..' && !segment.startsWith('.'),
  );
}

export function assertValidStorageKey(key: string): void {
  if (!isValidStorageKey(key)) throw new StorageError(`invalid storage key: ${key}`, 'invalid_key');
}

function slug(value: string, label: string): string {
  const out = value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  if (!out) throw new StorageError(`${label} yields an empty key segment`, 'invalid_key');
  return out;
}

/** ".jpg" → ".jpg"; "JPEG" → ".jpeg"; rejects blocked and odd extensions. */
export function normalizeExtension(ext: string | null | undefined): string {
  if (!ext) return '';
  const lower = (ext.startsWith('.') ? ext : `.${ext}`).toLowerCase();
  if (!/^\.[a-z0-9]{1,8}$/.test(lower))
    throw new StorageError(`invalid extension: ${ext}`, 'invalid_key');
  if ((BLOCKED_EXTENSIONS as readonly string[]).includes(lower))
    throw new StorageError(`extension ${lower} is not accepted`, 'invalid_key');
  return lower;
}

export interface BuildStorageKeyInput {
  organizationId: string | null;
  /** e.g. evidence, document, avatar, cms-media */
  purpose: string;
  /** UUID */
  fileId: string;
  ext?: string | null;
}

/** `org/<org>/<purpose>/<fileId><ext>` or `shared/<purpose>/<fileId><ext>`. */
export function buildStorageKey(input: BuildStorageKeyInput): string {
  if (!/^[a-z0-9-]{8,64}$/i.test(input.fileId))
    throw new StorageError(
      'fileId must be an identifier of 8–64 [a-z0-9-] characters',
      'invalid_key',
    );
  const scope = input.organizationId
    ? `org/${slug(input.organizationId, 'organizationId')}`
    : 'shared';
  const key = `${scope}/${slug(input.purpose, 'purpose')}/${input.fileId.toLowerCase()}${normalizeExtension(input.ext)}`;
  assertValidStorageKey(key);
  return key;
}

/**
 * `org/x/evidence/<id>.jpg` + variant `thumb` + `.webp` → `org/x/evidence/<id>.thumb.webp`.
 * Derivatives live in the derivatives bucket under this key.
 */
export function deriveVariantKey(originalKey: string, variant: string, ext: string): string {
  assertValidStorageKey(originalKey);
  const slash = originalKey.lastIndexOf('/');
  const dir = slash === -1 ? '' : originalKey.slice(0, slash + 1);
  const file = slash === -1 ? originalKey : originalKey.slice(slash + 1);
  const dot = file.indexOf('.');
  const base = dot === -1 ? file : file.slice(0, dot);
  const key = `${dir}${base}.${slug(variant, 'variant')}${normalizeExtension(ext)}`;
  assertValidStorageKey(key);
  return key;
}
