/**
 * Generates docs/guides/permission-matrix.md and docs/guides/workflow-transitions.md
 * from the authorization policy and the workflow state machines, so the
 * handoff documents can never drift from the code that enforces them.
 *
 * Run: pnpm docs:generate
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  IMPERSONATION_FORBIDDEN,
  MFA_REQUIRED_PERMISSIONS,
  ORG_PERMISSIONS,
  ORG_ROLES,
  ORG_ROLE_PERMISSIONS,
  PARTNER_ROLE_PERMISSIONS,
  STAFF_PERMISSIONS,
  STAFF_ROLES,
  STAFF_ROLE_DESCRIPTIONS,
  STAFF_ROLE_PERMISSIONS,
  TENANT_ROLE_PERMISSIONS,
} from '../src/authz/index';
import type { MachineDefinition } from '../src/workflow/machine';
import * as machines from '../src/workflow/machines';

const outDir = path.resolve(import.meta.dirname, '../../../docs/guides');
fs.mkdirSync(outDir, { recursive: true });

const generatedNote =
  '<!-- Generated by packages/domain/scripts/generate-docs.ts (pnpm docs:generate). Do not edit by hand. -->';

function permissionMatrix(): string {
  const lines: string[] = [];
  lines.push('# Permission matrix', '', generatedNote, '');
  lines.push(
    'Authorization is evaluated per request by `@simplexd/domain/authz`: a role grants a bundle of permissions, and the policy then checks the resource relationship (organisation membership, assignment, explicit grant) plus the relationship rules below. Row-level security in PostgreSQL is the second net. UI visibility is never authorization.',
    '',
  );
  lines.push('## Staff roles', '', '| Role | Scope | Explicit exclusions |', '|---|---|---|');
  for (const role of STAFF_ROLES) {
    const d = STAFF_ROLE_DESCRIPTIONS[role];
    lines.push(`| \`${role}\` | ${d.scope} | ${d.exclusions} |`);
  }
  lines.push('', '### Staff permissions by role', '');
  lines.push(
    `| Permission | ${STAFF_ROLES.map((r) => r.replace(/_/g, ' ')).join(' | ')} | MFA | Blocked during impersonation |`,
  );
  lines.push(`|---|${STAFF_ROLES.map(() => ':-:').join('|')}|:-:|:-:|`);
  for (const permission of STAFF_PERMISSIONS) {
    const cells = STAFF_ROLES.map((role) =>
      STAFF_ROLE_PERMISSIONS[role].has(permission) ? '✓' : '',
    );
    lines.push(
      `| \`${permission}\` | ${cells.join(' | ')} | ${MFA_REQUIRED_PERMISSIONS.has(permission) ? '✓' : ''} | ${IMPERSONATION_FORBIDDEN.has(permission) ? '✓' : ''} |`,
    );
  }
  lines.push('', '### Relationship rules enforced in addition to the role bundle', '');
  lines.push(
    '- `project_manager` and `inspector` only reach projects, service requests, visits and reports they are assigned to.',
    '- `reports.review` and `reports.release` are refused for the report author (no self-approval of a final report).',
    '- `market_data.publish` and `evidence.approve` are refused for the editor who created the change (no publishing your own material price or ranking change).',
    '- `finance.refunds.approve` is refused for the user who requested the refund; payouts need two different approvers.',
    '- `files.sensitive.read` is required for identity and legal documents; the finance role does not hold it.',
    '- Every permission marked MFA requires a verified authenticator on the staff account; the request is refused with `mfa_required` until enrolment is complete.',
    '- Permissions marked "blocked during impersonation" are refused while a support impersonation session is active, and every impersonated action is audited with the impersonation id.',
    '',
  );
  lines.push('## Customer organisation roles', '');
  lines.push(`| Permission | ${ORG_ROLES.join(' | ')} | Blocked during impersonation |`);
  lines.push(`|---|${ORG_ROLES.map(() => ':-:').join('|')}|:-:|`);
  for (const permission of ORG_PERMISSIONS) {
    const cells = ORG_ROLES.map((role) => (ORG_ROLE_PERMISSIONS[role].has(permission) ? '✓' : ''));
    lines.push(
      `| \`${permission}\` | ${cells.join(' | ')} | ${IMPERSONATION_FORBIDDEN.has(permission) ? '✓' : ''} |`,
    );
  }
  lines.push(
    '',
    'Organisation permissions only apply inside the organisation the user is a member of; a user who belongs to several organisations switches the active organisation, which resets cached private data.',
    '',
  );
  lines.push('## Tenants', '', 'A tenant membership grants only:', '');
  for (const p of TENANT_ROLE_PERMISSIONS) lines.push(`- \`${p}\``);
  lines.push(
    '',
    'Tenants see their own lease, balances, receipts, maintenance tickets, appointments and approved notices. They never see the owner ledger or other tenants.',
    '',
  );
  lines.push(
    '## Partners (contractors, vendors, surveyors, legal)',
    '',
    'A verified partner profile grants only:',
    '',
  );
  for (const p of PARTNER_ROLE_PERMISSIONS) lines.push(`- \`${p}\``);
  lines.push(
    '',
    'Every partner permission is additionally scoped to invitations and assignments naming that partner: no competitor submissions, no unassigned work.',
    '',
  );
  return lines.join('\n');
}

function isMachine(value: unknown): value is MachineDefinition<string> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'transitions' in value &&
    'states' in value &&
    'initial' in value
  );
}

function workflowTransitions(): string {
  const lines: string[] = [];
  lines.push('# Workflow transitions', '', generatedNote, '');
  lines.push(
    'Every workflow state lives in the database; transitions are explicit, permission-tagged and appended to a transition or audit log. A transition that is not listed here is refused with `invalid_transition`.',
    '',
  );
  const entries = Object.entries(machines).filter((e): e is [string, MachineDefinition<string>] =>
    isMachine(e[1]),
  );
  for (const [, def] of entries) {
    lines.push(`## ${def.name}`, '');
    lines.push(`States: ${def.states.map((s) => `\`${s}\``).join(', ')}.`);
    lines.push(
      `Initial: \`${def.initial}\`. Terminal: ${def.terminal.map((s) => `\`${s}\``).join(', ') || 'none'}.`,
      '',
    );
    lines.push(
      '| From | To | Who | Permission | Reason required | Effect |',
      '|---|---|---|---|:-:|---|',
    );
    for (const t of def.transitions) {
      const from = (Array.isArray(t.from) ? t.from : [t.from]).map((s) => `\`${s}\``).join(', ');
      lines.push(
        `| ${from} | \`${t.to}\` | ${t.by.join(', ')} | ${t.permission ? `\`${t.permission}\`` : ''} | ${t.reasonRequired ? '✓' : ''} | ${t.effect ?? ''} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

fs.writeFileSync(path.join(outDir, 'permission-matrix.md'), `${permissionMatrix()}\n`);
fs.writeFileSync(path.join(outDir, 'workflow-transitions.md'), `${workflowTransitions()}\n`);
process.stdout.write(
  `Wrote ${path.join(outDir, 'permission-matrix.md')} and workflow-transitions.md\n`,
);
