import type {
  OrgPermission,
  PartnerPermission,
  StaffPermission,
  TenantPermission,
} from './permissions';

export const STAFF_ROLES = [
  'super_admin',
  'operations_manager',
  'project_manager',
  'inspector',
  'finance',
  'data_editor',
  'data_approver',
  'content_editor',
  'support',
] as const;
export type StaffRole = (typeof STAFF_ROLES)[number];

export const ORG_ROLES = ['owner', 'member', 'adviser', 'approver', 'tenant'] as const;
export type OrgRole = (typeof ORG_ROLES)[number];

/**
 * Staff role matrix. Explicit exclusions from the brief are enforced by
 * omission here and by relationship rules in policy.ts (e.g. an inspector may
 * not approve their own final report; a data editor may not publish their own
 * material price or ranking change; finance has no sensitive-document access).
 */
export const STAFF_ROLE_PERMISSIONS: Record<StaffRole, ReadonlySet<StaffPermission>> = {
  super_admin: new Set<StaffPermission>([
    'platform.settings.manage',
    'platform.feature_flags.manage',
    'platform.break_glass',
    'access.staff_roles.manage',
    'access.partners.verify',
    'audit.read',
    'integrations.read',
    'integrations.manage',
    'integrations.test',
    'integrations.secrets.rotate',
    'integrations.payment_credentials.manage',
    'customers.read',
    'customers.manage',
    'customers.read_sensitive',
    'support.tickets.read',
    'support.tickets.manage',
    'support.impersonate',
    'market_data.read_drafts',
    'market_data.edit',
    'market_data.import',
    'market_data.publish',
    'market_data.policy.manage',
    'market_data.history.read',
    'content.edit',
    'content.publish',
    'content.media.manage',
    'leads.read',
    'leads.manage',
    'service_requests.read_all',
    'service_requests.triage',
    'service_requests.assign',
    'service_requests.override',
    'quotes.issue',
    'pricing.manage',
    'sla.manage',
    'projects.read_all',
    'projects.manage',
    'site_visits.perform',
    'reports.draft',
    'reports.review',
    'reports.release',
    'change_orders.staff_approve',
    'milestones.record_progress',
    'milestones.finance_authorize',
    'evidence.approve',
    'files.read_all',
    'files.sensitive.read',
    'finance.read',
    'finance.invoices.manage',
    'finance.allocations.manage',
    'finance.reconcile',
    'finance.refunds.request',
    'finance.refunds.approve',
    'finance.payouts.first_approve',
    'finance.payouts.second_approve',
    'finance.export',
    'finance.tax.manage',
    'tenders.manage',
    'bids.evaluate',
    'bids.open_sealed',
    'procurement.manage',
    'rentals.manage',
    'maintenance.manage',
    'estates.manage',
    'appointments.manage_all',
    'appointments.test_booking',
    'messages.read_all',
    'notifications.templates.manage',
    'notifications.test_send',
  ]),
  operations_manager: new Set<StaffPermission>([
    'audit.read',
    'integrations.read',
    'integrations.test',
    'customers.read',
    'customers.manage',
    'support.tickets.read',
    'support.tickets.manage',
    'market_data.read_drafts',
    'leads.read',
    'leads.manage',
    'service_requests.read_all',
    'service_requests.triage',
    'service_requests.assign',
    'service_requests.override',
    'quotes.issue',
    'pricing.manage',
    'sla.manage',
    'projects.read_all',
    'projects.manage',
    'reports.review',
    'reports.release',
    'change_orders.staff_approve',
    'milestones.record_progress',
    'evidence.approve',
    'files.read_all',
    'finance.read',
    'tenders.manage',
    'bids.evaluate',
    'procurement.manage',
    'rentals.manage',
    'maintenance.manage',
    'estates.manage',
    'appointments.manage_all',
    'appointments.test_booking',
    'messages.read_all',
    'notifications.templates.manage',
    'notifications.test_send',
    'access.partners.verify',
    // Excluded on purpose: integrations.manage, integrations.secrets.rotate,
    // integrations.payment_credentials.manage (needs a separate permission).
  ]),
  project_manager: new Set<StaffPermission>([
    'customers.read',
    'service_requests.read_all',
    'service_requests.triage',
    'service_requests.assign',
    'quotes.issue',
    'projects.read_all',
    'projects.manage',
    'site_visits.perform',
    'reports.draft',
    'reports.review',
    'reports.release',
    'change_orders.staff_approve',
    'milestones.record_progress',
    'evidence.approve',
    'files.read_all',
    'tenders.manage',
    'bids.evaluate',
    'procurement.manage',
    'appointments.manage_all',
    'messages.read_all',
    // Relationship rule: only assigned projects (policy.ts), no unrelated client access.
  ]),
  inspector: new Set<StaffPermission>([
    'site_visits.perform',
    'reports.draft',
    'milestones.record_progress',
    'files.read_all',
    // Cannot release funds or approve own final report (no finance.*, reports.release requires a different reviewer).
  ]),
  finance: new Set<StaffPermission>([
    'customers.read',
    'finance.read',
    'finance.invoices.manage',
    'finance.allocations.manage',
    'finance.reconcile',
    'finance.refunds.request',
    'finance.refunds.approve',
    'finance.payouts.first_approve',
    'finance.payouts.second_approve',
    'finance.export',
    'finance.tax.manage',
    'milestones.finance_authorize',
    'rentals.manage',
    'audit.read',
    // No files.sensitive.read: no unrestricted legal/identity-document access.
  ]),
  data_editor: new Set<StaffPermission>([
    'market_data.read_drafts',
    'market_data.edit',
    'market_data.import',
    'market_data.history.read',
    // Cannot publish own material price/ranking changes (no market_data.publish).
  ]),
  data_approver: new Set<StaffPermission>([
    'market_data.read_drafts',
    'market_data.edit',
    'market_data.import',
    'market_data.publish',
    'market_data.policy.manage',
    'market_data.history.read',
    // No silent deletion of history: enforced by append-only revisions.
  ]),
  content_editor: new Set<StaffPermission>([
    'content.edit',
    'content.publish',
    'content.media.manage',
    // No private project documents or payment access.
  ]),
  support: new Set<StaffPermission>([
    'customers.read',
    'support.tickets.read',
    'support.tickets.manage',
    'leads.read',
    'appointments.manage_all',
    // Masked finance/identity fields (no finance.read, no customers.read_sensitive),
    // impersonation only with explicit support.impersonate grant + feature flag.
  ]),
};

export const ORG_ROLE_PERMISSIONS: Record<OrgRole, ReadonlySet<OrgPermission>> = {
  owner: new Set<OrgPermission>([
    'org.read',
    'org.settings.manage',
    'org.members.invite',
    'org.members.manage',
    'org.properties.manage',
    'org.requests.create',
    'org.requests.cancel',
    'org.quotes.accept',
    'org.invoices.view',
    'org.invoices.pay',
    'org.documents.upload',
    'org.documents.view',
    'org.change_orders.approve',
    'org.milestones.accept',
    'org.reports.view',
    'org.messages.send',
    'org.appointments.manage',
    'org.scenarios.manage',
    'org.listings.manage',
    'org.leases.manage',
    'org.maintenance.request',
    'org.comment',
    'org.export',
  ]),
  member: new Set<OrgPermission>([
    'org.read',
    'org.members.invite',
    'org.properties.manage',
    'org.requests.create',
    'org.invoices.view',
    'org.invoices.pay',
    'org.documents.upload',
    'org.documents.view',
    'org.reports.view',
    'org.messages.send',
    'org.appointments.manage',
    'org.scenarios.manage',
    'org.listings.manage',
    'org.leases.manage',
    'org.maintenance.request',
    'org.comment',
    'org.export',
  ]),
  approver: new Set<OrgPermission>([
    'org.read',
    'org.invoices.view',
    'org.documents.view',
    'org.reports.view',
    'org.quotes.accept',
    'org.change_orders.approve',
    'org.milestones.accept',
    'org.messages.send',
    'org.comment',
  ]),
  adviser: new Set<OrgPermission>([
    'org.read',
    'org.documents.view',
    'org.reports.view',
    'org.invoices.view',
    'org.comment',
    'org.messages.send',
  ]),
  tenant: new Set<OrgPermission>([]),
};

export const TENANT_ROLE_PERMISSIONS: ReadonlySet<TenantPermission> = new Set<TenantPermission>([
  'tenant.lease.view',
  'tenant.balances.view',
  'tenant.receipts.view',
  'tenant.maintenance.request',
  'tenant.appointments.view',
  'tenant.notices.view',
  'tenant.messages.send',
]);

export const PARTNER_ROLE_PERMISSIONS: ReadonlySet<PartnerPermission> = new Set<PartnerPermission>([
  'partner.tenders.view_invited',
  'partner.bids.submit',
  'partner.assignments.view',
  'partner.reports.draft',
  'partner.evidence.upload',
  'partner.rfqs.respond',
  'partner.deliveries.view',
  'partner.invoices.submit',
  'partner.availability.manage',
]);

/** Human-readable descriptions for the permission matrix document. */
export const STAFF_ROLE_DESCRIPTIONS: Record<StaffRole, { scope: string; exclusions: string }> = {
  super_admin: {
    scope: 'Organisation settings, roles, provider setup, break-glass operations',
    exclusions: 'No routine sharing of secrets or bypass without audit',
  },
  operations_manager: {
    scope: 'Staff assignments, workflow overrides, service delivery',
    exclusions: 'Cannot change payment credentials without separate permission',
  },
  project_manager: {
    scope: 'Assigned projects, budgets, requests and report review',
    exclusions: 'No unrelated client access',
  },
  inspector: {
    scope: 'Assigned visits, draft findings, uploads',
    exclusions: 'Cannot release funds or approve own final report by default',
  },
  finance: {
    scope: 'Invoices, reconciliation, authorized refunds, owner statements',
    exclusions: 'No unrestricted legal/identity-document access',
  },
  data_editor: {
    scope: 'Draft locations, sources and observations',
    exclusions: 'Cannot publish own material price/ranking changes',
  },
  data_approver: {
    scope: 'Review/publish data and score policies',
    exclusions: 'No silent deletion of history',
  },
  content_editor: {
    scope: 'Pages, media and SEO drafts',
    exclusions: 'No private project documents or payment access',
  },
  support: {
    scope: 'Assigned customer tickets and limited profile',
    exclusions: 'Masked finance/identity fields, no unrestricted impersonation',
  },
};
